// Preguntas guía del Diario — 90 preguntas, una por día del año, cíclicas
// cada ~3 meses (ver todayPreguntaIndex en App.jsx: (díaDelAño - 1) % 90).
export const PREGUNTAS_DIARIO = [
  "¿Por qué le das gracias a Dios hoy?",
  "¿Dónde sentiste su presencia en tu día, aunque fuera un instante?",
  "¿Qué llevabas pesado hoy, y se lo entregaste?",
  "¿A quién viste hoy que también carga algo, sin decirlo?",
  "¿Qué momento de silencio tuviste hoy, aunque fuera breve?",
  "¿Qué te sorprendió hoy, para bien?",
  "¿Por quién oraste hoy sin que lo supiera?",
  "¿Qué palabra del Evangelio de hoy se quedó contigo?",
  "¿A quién le debes una palabra de gracias, y no se la has dicho?",
  "¿Qué miedo llevaste hoy al altar de tu corazón?",
  "¿Dónde te costó ser paciente hoy?",
  "¿Qué pequeña cosa de hoy fue en realidad un regalo?",
  "¿A quién perdonaste hoy, aunque fuera en silencio?",
  "¿Qué necesitas pedirle a Dios que aún no le has pedido?",
  "¿Cuándo dejaste de correr hoy, aunque fuera un momento?",
  "¿Qué de tu día de hoy volverías a vivir?",
  "¿A quién ayudaste hoy sin que te lo pidiera?",
  "¿Qué te costó agradecer hoy, y por qué?",
  "¿Dónde viste a Dios en la gente de hoy?",
  "¿Qué carga soltaste hoy que ya no era tuya?",
  "¿Qué aprendiste hoy de alguien que no esperabas?",
  "¿Cuál fue tu Nazaret hoy — lo pequeño, lo escondido, lo fiel?",
  "¿Qué oración quedó a medias hoy, y quieres terminarla ahora?",
  "¿A quién extrañaste hoy en tus oraciones?",
  "¿Qué de hoy te hizo sentir cercano a los tuyos?",
  "¿Dónde encontraste paz en medio del ruido de hoy?",
  "¿Qué le dirías a Dios si supieras que te escucha ahora mismo?",
  "¿Qué de tu día merece ser recordado dentro de un año?",
  "¿A quién bendices hoy, aunque esté lejos?",
  "¿Con qué palabra cerrarías este día, si solo pudieras usar una?",
  "¿Qué de hoy te recordó que no estás solo?",
  "¿A quién juzgaste hoy sin querer, y qué harías distinto?",
  "¿Qué palabra amable recibiste hoy, y de quién?",
  "¿Dónde tuviste que elegir entre el ruido y el silencio, y qué elegiste?",
  "¿Qué de tu fe se sintió más real hoy que ayer?",
  "¿A quién le hiciste falta hoy, y llegaste?",
  "¿Qué costumbre pequeña de hoy es en realidad una forma de orar?",
  "¿Qué soltaste hoy que llevabas cargando hace tiempo?",
  "¿Dónde viste la fidelidad de alguien hoy?",
  "¿Qué te hizo bajar la guardia hoy, para bien?",
  "¿A quién te gustaría parecerte más, después de hoy?",
  "¿Qué de la Creación te habló hoy — un cielo, un árbol, una luz?",
  "¿Cuál fue tu instante de fe más pequeño hoy?",
  "¿Qué herida de hoy puedes ofrecer en vez de esconder?",
  "¿A quién bendijiste hoy sin decirlo en voz alta?",
  "¿Qué te costó soltar hoy, y qué te costaría soltar mañana?",
  "¿Dónde sentiste que Dios se adelantó a lo que ibas a pedir?",
  "¿Qué gesto simple de hoy fue en realidad amor?",
  "¿Qué verdad sobre ti misma o ti mismo aceptaste hoy?",
  "¿A quién le debes hoy un abrazo, aunque sea a la distancia?",
  "¿Qué de hoy fue una pequeña resurrección?",
  "¿Dónde tuviste que confiar sin ver el camino completo?",
  "¿Qué oración corta rezaste hoy sin darte cuenta?",
  "¿A quién viste hoy como Dios lo ve?",
  "¿Qué de hoy te enseñó a esperar?",
  "¿Cuál fue tu \"sí\" más difícil de hoy?",
  "¿Qué de tu día de hoy fue semilla, aunque el fruto tarde?",
  "¿A quién le agradeces su paciencia contigo hoy?",
  "¿Dónde encontraste consuelo hoy sin buscarlo?",
  "¿Qué de hoy te hizo sentir hijo o hija, no huérfano?",
  "¿Qué límite pusiste hoy con amor, no con rabia?",
  "¿A quién le mostraste hoy que no está solo?",
  "¿Qué de tu día de hoy fue un pequeño Nazaret — silencioso, fiel, sin aplausos?",
  "¿Dónde tuviste que perdonarte a ti mismo hoy?",
  "¿Qué señal de esperanza viste hoy, aunque fuera diminuta?",
  "¿A quién extrañas hoy, y qué le dirías si estuviera cerca?",
  "¿Qué de hoy fue más gracia que esfuerzo?",
  "¿Cuál fue tu descanso verdadero de hoy?",
  "¿Dónde sentiste que tu oración fue escuchada, aunque no como esperabas?",
  "¿Qué de hoy quisieras contarle a Dios como si fuera tu mejor amigo?",
  "¿A quién ayudaste hoy a llevar su cruz, aunque fuera un momento?",
  "¿Qué costumbre de fe de tu familia agradeces hoy?",
  "¿Dónde viste humildad hoy, y en quién?",
  "¿Qué de hoy fue un recordatorio de que el tiempo es un regalo?",
  "¿A quién te gustaría pedirle perdón, aunque sea en tu corazón?",
  "¿Qué momento de hoy mereció más atención de la que le diste?",
  "¿Dónde sentiste que no merecías tanto bien, y aun así lo recibiste?",
  "¿Qué de hoy fue un eco del Evangelio en tu vida cotidiana?",
  "¿A quién viste crecer en fe hoy, aunque fuera un pequeño paso?",
  "¿Qué de hoy fue más silencio que palabras, y qué te dijo?",
  "¿Cuál fue tu manera de amar hoy sin decir \"te amo\"?",
  "¿Dónde tuviste que elegir la verdad, aunque costara?",
  "¿Qué de hoy te hizo mirar hacia adelante con esperanza?",
  "¿A quién le debes hoy una oración, y aún no se la has ofrecido?",
  "¿Qué de tu jornada de hoy fue trabajo hecho oración?",
  "¿Dónde encontraste a Dios en lo ordinario de hoy?",
  "¿Qué de hoy fue una pequeña muerte que aceptaste con paz?",
  "¿A quién le dijiste \"gracias\" hoy y lo sentiste de verdad?",
  "¿Qué de tu día de hoy te gustaría que Dios recordara contigo?",
  "¿Con qué imagen cerrarías este día, si tuvieras que dibujarlo?",
];
