// Preguntas guía del Diario — una por día del mes (índice 0 = día 1 ... índice 29 = día 30).
// El día 31 reutiliza la pregunta del día 30 (ver todayPreguntaIndex en App.jsx).
export const PREGUNTAS_DIARIO = [
  "¿Por qué le das gracias a Dios hoy?",
  "¿Dónde sentiste su presencia en tu día, aunque fuera un instante?",
  "¿Qué llevabas pesado hoy, y se lo entregaste?",
  "¿A quién viste hoy que también carga algo, sin decirlo?",
  "¿Qué momento de silencio tuviste hoy, aunque fuera breve?",
  "¿Qué te sorprendió hoy, para bien?",
  "¿Por quién oraste hoy sin que lo supiera?",
  "¿Qué palabra del Evangelio de hoy se quedó contigo?",
  "¿A quién le debes una palabra de gracias, y no se la has dicho?",
  "¿Qué miedo llevaste hoy al altar de tu corazón?",
  "¿Dónde te costó ser paciente hoy?",
  "¿Qué pequeña cosa de hoy fue en realidad un regalo?",
  "¿A quién perdonaste hoy, aunque fuera en silencio?",
  "¿Qué necesitas pedirle a Dios que aún no le has pedido?",
  "¿Cuándo dejaste de correr hoy, aunque fuera un momento?",
  "¿Qué de tu día de hoy volverías a vivir?",
  "¿A quién ayudaste hoy sin que te lo pidiera?",
  "¿Qué te costó agradecer hoy, y por qué?",
  "¿Dónde viste a Dios en la gente de hoy?",
  "¿Qué carga soltaste hoy que ya no era tuya?",
  "¿Qué aprendiste hoy de alguien que no esperabas?",
  "¿Cuál fue tu Nazaret hoy — lo pequeño, lo escondido, lo fiel?",
  "¿Qué oración quedó a medias hoy, y quieres terminarla ahora?",
  "¿A quién extrañaste hoy en tus oraciones?",
  "¿Qué de hoy te hizo sentir cercano a los tuyos?",
  "¿Dónde encontraste paz en medio del ruido de hoy?",
  "¿Qué le dirías a Dios si supieras que te escucha ahora mismo?",
  "¿Qué de tu día merece ser recordado dentro de un año?",
  "¿A quién bendices hoy, aunque esté lejos?",
  "¿Con qué palabra cerrarías este día, si solo pudieras usar una?",
];
