const SANTOS = {
  '01-01': { nombre: 'Solemnidad de María Madre de Dios', bio: 'Celebración de María como Madre de Dios, primera fiesta mariana del año litúrgico. Muy venerada en Colombia.', frase: 'Santa María, Madre de Dios, ruega por nosotros.' },
  '01-02': { nombre: 'Santos Basilio y Gregorio', bio: 'Doctores de la Iglesia del siglo IV, pilares de la teología cristiana y defensores de la fe.', frase: 'La teología al servicio de Dios y de los hombres.' },
  '01-03': { nombre: 'Santísimo Nombre de Jesús', bio: 'Celebración del nombre de Jesús que significa Salvador. Devoción muy arraigada en Colombia.', frase: 'En el nombre de Jesús toda rodilla se dobla.' },
  '01-04': { nombre: 'Santa Isabel Ana Seton', bio: 'Primera santa nacida en Estados Unidos, fundadora de las Hijas de la Caridad en América.', frase: 'La caridad todo lo puede.' },
  '01-05': { nombre: 'San Juan Nepomuceno Neumann', bio: 'Obispo misionero en América, defensor de la educación católica.', frase: 'Dios primero en todo.' },
  '01-06': { nombre: 'Epifanía del Señor', bio: 'Manifestación de Jesús a los Reyes Magos. Fiesta de gran tradición en Colombia y Latinoamérica.', frase: 'Hemos visto su estrella y venimos a adorarlo.' },
  '01-07': { nombre: 'San Raimundo de Peñafort', bio: 'Dominico español, gran jurista canónico y evangelizador del siglo XIII.', frase: 'La ley al servicio de la misericordia.' },
  '01-08': { nombre: 'San Severino de Nórica', bio: 'Monje y apóstol de Austria del siglo V, defensor de los pobres y cautivos.', frase: 'Servir a los pobres es encontrar a Cristo.' },
  '01-09': { nombre: 'San Julián de Toledo', bio: 'Arzobispo visigodo del siglo VII, doctor y defensor de la fe católica en España.', frase: 'La fe ilumina la razón.' },
  '01-10': { nombre: 'San Gonzalo de Amarante', bio: 'Sacerdote portugués del siglo XIII conocido por su humildad y amor a los pobres.', frase: 'En los pobres está el rostro de Cristo.' },
  '01-11': { nombre: 'San Higinio', bio: 'Papa mártir del siglo II que organizó la jerarquía de la Iglesia primitiva.', frase: 'La Iglesia es una, santa, católica y apostólica.' },
  '01-12': { nombre: 'San Nazario', bio: 'Mártir romano del siglo I, discípulo de San Pedro que evangelizó Milán.', frase: 'El martirio es el bautismo de sangre.' },
  '01-13': { nombre: 'San Hilario de Poitiers', bio: 'Doctor de la Iglesia del siglo IV, defensor de la divinidad de Cristo contra el arrianismo.', frase: 'Cristo es verdadero Dios y verdadero hombre.' },
  '01-14': { nombre: 'San Félix de Nola', bio: 'Sacerdote mártir del siglo III que vendió sus bienes para rescatar cautivos.', frase: 'La libertad del alma vale más que la del cuerpo.' },
  '01-15': { nombre: 'San Pablo Ermitaño', bio: 'Primer ermitaño cristiano del siglo III, vivió 90 años en el desierto de Egipto.', frase: 'El silencio es el idioma de Dios.' },
  '01-16': { nombre: 'San Marcelo I', bio: 'Papa del siglo IV que guio la Iglesia durante la persecución de Diocleciano.', frase: 'El pastor da la vida por sus ovejas.' },
  '01-17': { nombre: 'San Antonio Abad', bio: 'Padre del monaquismo cristiano, vivió en el desierto egipcio y fundó la vida monástica. Muy popular en Colombia.', frase: 'Conoce a Dios y conócete a ti mismo.' },
  '01-18': { nombre: 'Santa Prisca', bio: 'Mártir romana del siglo I, una de las primeras vírgenes consagradas a Cristo.', frase: 'La virginidad es anticipo del cielo.' },
  '01-19': { nombre: 'San Canuto de Dinamarca', bio: 'Rey mártir de Dinamarca del siglo XI, defendió la fe y la justicia hasta la muerte.', frase: 'El poder al servicio de Dios y del pueblo.' },
  '01-20': { nombre: 'San Fabián y San Sebastián', bio: 'Mártires romanos muy venerados. San Sebastián es patrono de los soldados y los atletas.', frase: 'La valentía del cristiano viene de Cristo.' },
  '01-21': { nombre: 'Santa Inés de Roma', bio: 'Mártir romana de 12 años que prefirió morir antes que renegar de su fe. Patrona de las jóvenes.', frase: 'Nada me separará del amor de Cristo.' },
  '01-22': { nombre: 'San Vicente de Zaragoza', bio: 'Diácono mártir español del siglo IV, patrono de los vinicultores y los estudiantes.', frase: 'El diácono sirve en la mesa del Señor y en la mesa de los pobres.' },
  '01-23': { nombre: 'San Ildefonso de Toledo', bio: 'Arzobispo de Toledo del siglo VII, gran defensor de la virginidad de María.', frase: 'María es la más perfecta discípula de Cristo.' },
  '01-24': { nombre: 'San Francisco de Sales', bio: 'Doctor de la Iglesia y obispo de Ginebra, patrono de los periodistas y escritores católicos.', frase: 'Nada se consigue con la dureza; todo con el amor y la dulzura.' },
  '01-25': { nombre: 'Conversión de San Pablo', bio: 'Celebración de la conversión de Saulo de Tarso camino a Damasco. Fiesta de gran importancia misionera.', frase: 'Ya no vivo yo, sino que Cristo vive en mí.' },
  '01-26': { nombre: 'Santos Timoteo y Tito', bio: 'Discípulos y colaboradores de San Pablo, primeros obispos de Éfeso y Creta.', frase: 'Predica la palabra a tiempo y a destiempo.' },
  '01-27': { nombre: 'Santa Ángela de Mérici', bio: 'Fundadora de las Ursulinas, pionera en la educación de la mujer en el siglo XVI.', frase: 'Educar a la mujer es educar a la familia.' },
  '01-28': { nombre: 'Santo Tomás de Aquino', bio: 'Doctor Angélico, el mayor teólogo de la historia de la Iglesia. Patrono de los estudiantes y las universidades.', frase: 'La fe busca comprender.' },
  '01-29': { nombre: 'San Valerio de Zaragoza', bio: 'Obispo español del siglo IV, compañero en el martirio de San Vicente.', frase: 'El obispo es pastor y padre de su pueblo.' },
  '01-30': { nombre: 'Santa Martina', bio: 'Mártir romana del siglo III, patrona de Roma junto con San Pedro.', frase: 'Cristo es la roca sobre la que todo se edifica.' },
  '01-31': { nombre: 'San Juan Bosco', bio: 'Fundador de los Salesianos, apóstol de la juventud del siglo XIX. Muy venerado en Colombia.', frase: 'Dame almas, llévate lo demás.' },
  '02-01': { nombre: 'San Ignacio de Antioquía', bio: 'Obispo mártir del siglo II, discípulo de San Juan Apóstol. Sus cartas son tesoro de la fe primitiva.', frase: 'Soy trigo de Dios y seré molido por los dientes de las fieras.' },
  '02-02': { nombre: 'Presentación del Señor', bio: 'Celebración de la presentación de Jesús en el Templo. Fiesta de la Candelaria, muy venerada en Colombia.', frase: 'Luz para iluminar a las naciones.' },
  '02-03': { nombre: 'San Blas', bio: 'Obispo mártir del siglo IV, patrono de los enfermos de garganta. Muy popular en Colombia.', frase: 'San Blas bendice tu garganta para que alabe a Dios.' },
  '02-04': { nombre: 'San Andrés Corsini', bio: 'Obispo carmelita florentino del siglo XIV, conocido por su conversión radical y amor a los pobres.', frase: 'La conversión es el primer milagro.' },
  '02-05': { nombre: 'Santa Águeda', bio: 'Mártir siciliana del siglo III, patrona de las mujeres con cáncer de mama y de las nodrizas.', frase: 'Mi corazón está confirmado en Cristo.' },
  '02-06': { nombre: 'San Pablo Miki y compañeros', bio: '26 mártires crucificados en Japón en 1597. Primeros mártires de Asia Oriental.', frase: 'Muero por predicar la doctrina de Cristo.' },
  '02-07': { nombre: 'San Ricardo de Lucca', bio: 'Rey anglosajón peregrino del siglo VIII que murió en Lucca camino a Roma.', frase: 'El camino a Dios pasa por la entrega total.' },
  '02-08': { nombre: 'San Jerónimo Emiliani', bio: 'Fundador de los Somascos, patrono de los huérfanos y los abandonados.', frase: 'Los huérfanos son hijos predilectos de Dios.' },
  '02-09': { nombre: 'Santa Apolonia', bio: 'Mártir alejandrina del siglo III, patrona de los dentistas y los enfermos de dientes.', frase: 'El dolor ofrecido a Cristo se convierte en gozo.' },
  '02-10': { nombre: 'Santa Escolástica', bio: 'Hermana gemela de San Benito, fundadora del monaquismo femenino en Occidente.', frase: 'El amor a Dios supera toda regla.' },
  '02-11': { nombre: 'Nuestra Señora de Lourdes', bio: 'Aparición de la Virgen a Bernadette en Francia en 1858. Advocación muy venerada en Colombia.', frase: 'Soy la Inmaculada Concepción.' },
  '02-12': { nombre: 'San Damián López de Madrid', bio: 'Franciscano español mártir en China del siglo XVII, evangelizador heroico de Asia.', frase: 'El evangelio no tiene fronteras.' },
  '02-13': { nombre: 'Santa Catalina de Ricci', bio: 'Dominica florentina del siglo XVI que recibió los estigmas de Cristo.', frase: 'Padecer es el camino más corto hacia Dios.' },
  '02-14': { nombre: 'San Valentín', bio: 'Mártir romano del siglo III. Su fiesta coincide con la celebración del amor. Patrono de los enamorados.', frase: 'El amor verdadero viene de Dios y lleva a Dios.' },
  '02-15': { nombre: 'San Claudio de Condat', bio: 'Abad del siglo VII que transformó su monasterio en centro de evangelización de Europa.', frase: 'La oración y el trabajo santifican el mundo.' },
  '02-16': { nombre: 'San Onésimo', bio: 'Esclavo convertido por San Pablo, luego obispo y mártir. Su historia es de conversión radical.', frase: 'En Cristo no hay esclavo ni libre.' },
  '02-17': { nombre: 'Los Siete Fundadores de los Servitas', bio: 'Siete mercaderes florentinos del siglo XIII que lo dejaron todo para fundar la Orden de los Siervos de María.', frase: 'Todo por María, todo con María.' },
  '02-18': { nombre: 'San Francisco Regis Clet', bio: 'Mártir lazarista francés en China del siglo XIX, evangelizador heroico.', frase: 'La misión vale más que la vida.' },
  '02-19': { nombre: 'San Álvaro de Córdoba', bio: 'Dominico español del siglo XV, misionero y reformador, introdujo el Via Crucis en España.', frase: 'El Via Crucis es el camino del amor.' },
  '02-20': { nombre: 'San Eleuterio', bio: 'Obispo mártir del siglo V, defensor de la fe en tiempos de invasiones bárbaras.', frase: 'La fe es el escudo del cristiano.' },
  '02-21': { nombre: 'San Pedro Damián', bio: 'Doctor de la Iglesia del siglo XI, reformador monástico y cardenal.', frase: 'La penitencia es medicina del alma.' },
  '02-22': { nombre: 'Cátedra de San Pedro', bio: 'Celebración del primado de Pedro como fundamento de la Iglesia. Fiesta de unidad católica.', frase: 'Tú eres Pedro y sobre esta roca edificaré mi Iglesia.' },
  '02-23': { nombre: 'San Policarpo de Esmirna', bio: 'Obispo mártir del siglo II, discípulo de San Juan Apóstol, uno de los Padres Apostólicos.', frase: 'Ochenta y seis años llevo sirviendo a Cristo y nunca me ha hecho mal.' },
  '02-24': { nombre: 'San Modesto de Tréveris', bio: 'Obispo del siglo IV que reconstruyó la Iglesia tras las persecuciones romanas.', frase: 'La Iglesia siempre resurge de las cenizas.' },
  '02-25': { nombre: 'San Cesáreo de Nazianzeno', bio: 'Médico del siglo IV, hermano de San Gregorio, que entregó sus bienes a los pobres antes de morir.', frase: 'La medicina del alma vale más que la del cuerpo.' },
  '02-26': { nombre: 'San Porfirio de Gaza', bio: 'Obispo del siglo V que transformó Gaza convirtiendo a miles al cristianismo.', frase: 'La conversión es obra de Dios, no del hombre.' },
  '02-27': { nombre: 'San Gabriel de la Dolorosa', bio: 'Pasionista italiano del siglo XIX, modelo de juventud consagrada a María.', frase: 'María es el camino más corto hacia Jesús.' },
  '02-28': { nombre: 'San Román de Condat', bio: 'Monje del siglo V, fundador del monaquismo en el Jura francés.', frase: 'El desierto interior es donde Dios habla.' },
  '02-29': { nombre: 'San Oswaldo de Worcester', bio: 'Obispo y reformador del siglo X, renovó la vida monástica en Inglaterra.', frase: 'La reforma de la Iglesia comienza por uno mismo.' },
  '03-01': { nombre: 'San Albino de Angers', bio: 'Obispo del siglo VI que defendió la dignidad del matrimonio y rescató esclavos.', frase: 'La dignidad humana es don de Dios.' },
  '03-02': { nombre: 'San Simplicio', bio: 'Papa del siglo V que guió la Iglesia durante la caída del Imperio Romano de Occidente.', frase: 'La Iglesia es roca en medio de la tormenta.' },
  '03-03': { nombre: 'Santa Catalina Drexel', bio: 'Fundadora americana del siglo XX que dedicó su herencia millonaria a los afroamericanos e indígenas.', frase: 'Lo que haces por los pobres, lo haces por Cristo.' },
  '03-04': { nombre: 'San Casimiro de Polonia', bio: 'Príncipe polaco del siglo XV, modelo de castidad y justicia, patrono de Polonia y Lituania.', frase: 'La pureza de corazón es la mayor riqueza.' },
  '03-05': { nombre: 'San Juan José de la Cruz', bio: 'Franciscano napolitano del siglo XVIII, místico y hacedor de milagros.', frase: 'La oración transforma el corazón.' },
  '03-06': { nombre: 'San Coleta de Corbie', bio: 'Clarisa francesa del siglo XV que reformó la Orden de Santa Clara con gran rigor y amor.', frase: 'La pobreza voluntaria es riqueza celestial.' },
  '03-07': { nombre: 'Santas Perpetua y Felicidad', bio: 'Mártires africanas del siglo III. Perpetua era noble y Felicidad esclava — iguales ante Cristo.', frase: 'En Cristo no hay distinción de personas.' },
  '03-08': { nombre: 'San Juan de Dios', bio: 'Fundador de los Hermanos Hospitalarios, patrono de los enfermos y hospitales. Muy venerado en Colombia.', frase: 'Haced el bien, hermanos, y no os preocupéis por el resto.' },
  '03-09': { nombre: 'Santa Francisca Romana', bio: 'Esposa, madre y fundadora del siglo XV, modelo de santidad en la vida familiar.', frase: 'La familia es la Iglesia doméstica.' },
  '03-10': { nombre: 'San Macario de Jerusalén', bio: 'Obispo del siglo IV que reconstruyó los Santos Lugares y presenció el hallazgo de la Santa Cruz.', frase: 'La cruz de Cristo es nuestra gloria.' },
  '03-11': { nombre: 'San Eulogio de Córdoba', bio: 'Sacerdote mártir español del siglo IX que resistió la persecución islámica en Al-Ándalus.', frase: 'La fe no se rinde ante la persecución.' },
  '03-12': { nombre: 'San Gregorio Magno', bio: 'Papa y Doctor de la Iglesia del siglo VI, reformador litúrgico y evangelizador de Europa.', frase: 'El siervo de los siervos de Dios.' },
  '03-13': { nombre: 'San Rodrigo de Córdoba', bio: 'Sacerdote mártir español del siglo IX, víctima de la persecución en Al-Ándalus.', frase: 'Morir por Cristo es vivir para siempre.' },
  '03-14': { nombre: 'Santa Matilde de Alemania', bio: 'Reina alemana del siglo X, modelo de caridad y madre de emperadores.', frase: 'El poder se ejerce con humildad y caridad.' },
  '03-15': { nombre: 'San Clemente María Hofbauer', bio: 'Redentorista bohemio del siglo XIX, apóstol de Viena y patrono de la ciudad.', frase: 'La misión del cristiano es evangelizar.' },
  '03-16': { nombre: 'San Agustín de Canterbury', bio: 'Benedictino del siglo VI enviado por San Gregorio Magno a evangelizar Inglaterra.', frase: 'El evangelio transforma las naciones.' },
  '03-17': { nombre: 'San Patricio de Irlanda', bio: 'Apóstol de Irlanda del siglo V, esclavo convertido en misionero. Patrono de Irlanda.', frase: 'Cristo delante de mí, Cristo detrás de mí, Cristo en mí.' },
  '03-18': { nombre: 'San Cirilo de Jerusalén', bio: 'Doctor de la Iglesia del siglo IV, gran catequista y defensor de la Eucaristía.', frase: 'Este es mi Cuerpo, esto es mi Sangre.' },
  '03-19': { nombre: 'San José Esposo de María', bio: 'Patrono de la Iglesia Universal, de los trabajadores y de Colombia. Fiesta de guardar en Colombia.', frase: 'José, hombre justo, guardián del Redentor.' },
  '03-20': { nombre: 'San Cútberto de Lindisfarne', bio: 'Obispo anglosajón del siglo VII, apóstol del norte de Inglaterra y gran taumaturgo.', frase: 'La oración es el aliento del alma.' },
  '03-21': { nombre: 'San Nicolás de Flüe', bio: 'Campesino suizo del siglo XV que se convirtió en ermitaño y pacificó a Suiza. Patrono de Suiza.', frase: 'Dios mío y mi todo.' },
  '03-22': { nombre: 'Santa Lea de Roma', bio: 'Viuda romana del siglo IV que vendió sus bienes y entró en un monasterio para servir a Dios.', frase: 'La viudez consagrada es anticipo del cielo.' },
  '03-23': { nombre: 'San Toribio de Mogrovejo', bio: 'Arzobispo de Lima del siglo XVI, gran evangelizador de América del Sur. Canonizó a Rosa de Lima.', frase: 'El tiempo es corto, la eternidad es larga.' },
  '03-24': { nombre: 'San Óscar Romero', bio: 'Arzobispo mártir de El Salvador del siglo XX, defensor de los pobres asesinado en 1980. Patrono de América Latina.', frase: 'Si me matan, resucitaré en el pueblo salvadoreño.' },
  '03-25': { nombre: 'Anunciación del Señor', bio: 'El Ángel Gabriel anuncia a María que será Madre de Dios. Fiesta de guardar en Colombia.', frase: 'He aquí la esclava del Señor, hágase en mí según tu palabra.' },
  '03-26': { nombre: 'San Braulio de Zaragoza', bio: 'Obispo español del siglo VII, gran intelectual y amigo de San Isidoro de Sevilla.', frase: 'La cultura al servicio de la fe.' },
  '03-27': { nombre: 'San Ruperto de Salzburgo', bio: 'Obispo misionero del siglo VII que evangelizó Austria y fundó Salzburgo.', frase: 'El misionero lleva a Cristo donde Cristo no está.' },
  '03-28': { nombre: 'San Sixto III', bio: 'Papa del siglo V que construyó la Basílica de Santa María Mayor en Roma.', frase: 'María es la morada de Dios entre los hombres.' },
  '03-29': { nombre: 'San Jonás y San Baraquisio', bio: 'Mártires persas del siglo IV, hermanos que murieron juntos por su fe en Cristo.', frase: 'Unidos en Cristo, unidos en el martirio.' },
  '03-30': { nombre: 'San Juan Clímaco', bio: 'Monje del siglo VI, autor de la Escala del Paraíso, clásico de la espiritualidad oriental.', frase: 'La humildad es la escalera hacia Dios.' },
  '03-31': { nombre: 'Santa Balbina', bio: 'Mártir romana del siglo II, hija del mártir San Quirino. Patrona de las mujeres con escrófulas.', frase: 'La fe sana el cuerpo y el alma.' },
  '04-01': { nombre: 'San Hugo de Grenoble', bio: 'Obispo francés del siglo XI que apoyó a San Bruno en la fundación de la Cartuja.', frase: 'La soledad con Dios es la mayor riqueza.' },
  '04-02': { nombre: 'San Francisco de Paula', bio: 'Fundador de los Mínimos del siglo XV, patrono de los marineros italianos. Muy venerado en Colombia.', frase: 'Charitas — la caridad lo es todo.' },
  '04-03': { nombre: 'San Ricardo de Chichester', bio: 'Obispo inglés del siglo XIII, defensor de los derechos de la Iglesia ante el rey.', frase: 'Conocerte más claramente, amarte más sinceramente, seguirte más de cerca.' },
  '04-04': { nombre: 'San Isidoro de Sevilla', bio: 'Doctor de la Iglesia del siglo VII, el último gran Padre latino y patrono de internet.', frase: 'El saber sin humildad es soberbia.' },
  '04-05': { nombre: 'San Vicente Ferrer', bio: 'Dominico del siglo XIV, gran predicador misionero que recorrió Europa convirtiendo multitudes.', frase: 'Temed el juicio de Dios.' },
  '04-06': { nombre: 'San Celestino I', bio: 'Papa del siglo V que combatió las herejías del pelagianismo y nestorianismo.', frase: 'La gracia de Dios es necesaria para todo bien.' },
  '04-07': { nombre: 'San Juan Bautista de la Salle', bio: 'Fundador de los Hermanos de las Escuelas Cristianas, patrono de los educadores.', frase: 'Vivid Jesús en vuestros corazones, para siempre.' },
  '04-08': { nombre: 'San Alberto de Jerusalén', bio: 'Patriarca de Jerusalén del siglo XII que escribió la Regla del Carmelo.', frase: 'Medita la ley del Señor día y noche.' },
  '04-09': { nombre: 'Santa María Cleofé', bio: 'Familiar de la Virgen María, estuvo presente en la Crucifixión y fue testigo de la Resurrección.', frase: 'Junto a la cruz de Jesús estaba su madre.' },
  '04-10': { nombre: 'San Ezequiel Moreno', bio: 'Obispo agustino recoleto español del siglo XIX, misionero en Colombia. Beatificado por Juan Pablo II.', frase: 'Colombia en mi corazón y en mi oración.' },
  '04-11': { nombre: 'San Estanislao de Cracovia', bio: 'Obispo mártir polaco del siglo XI, patrono de Polonia. Murió por defender la moralidad del rey.', frase: 'La justicia vale más que la vida.' },
  '04-12': { nombre: 'San Zenón de Verona', bio: 'Obispo africano del siglo IV que evangelizó Verona y combatió el arrianismo.', frase: 'Cristo es la verdad que libera.' },
  '04-13': { nombre: 'San Martín I', bio: 'Papa mártir del siglo VII que defendió la fe ortodoxa contra la herejía monotelita.', frase: 'El Papa sirve a la verdad, no al poder.' },
  '04-14': { nombre: 'San Tiburcio y Compañeros', bio: 'Mártires romanos del siglo III, ejemplo de fortaleza en la persecución de Diocleciano.', frase: 'La sangre de los mártires es semilla de cristianos.' },
  '04-15': { nombre: 'Santa Anastasia Patricia', bio: 'Virgen del siglo VI que huyó a Egipto para consagrarse a Dios lejos de la corte imperial.', frase: 'Solo Dios basta.' },
  '04-16': { nombre: 'Santa Bernadette Soubirous', bio: 'Vidente de Lourdes del siglo XIX, humilde pastora a quien se apareció la Virgen Inmaculada.', frase: 'Soy la Inmaculada Concepción.' },
  '04-17': { nombre: 'San Aniceto', bio: 'Papa mártir del siglo II, recibió en Roma a San Policarpo de Esmirna para tratar la fecha de Pascua.', frase: 'La unidad de la Iglesia es don del Espíritu.' },
  '04-18': { nombre: 'San Galdino de Milán', bio: 'Cardenal y arzobispo del siglo XII que reconstruyó la diócesis de Milán tras las guerras.', frase: 'El pastor reconstruye lo que la guerra destruye.' },
  '04-19': { nombre: 'San León IX', bio: 'Papa reformador del siglo XI que renovó la Iglesia combatiendo la simonía y el nicolaísmo.', frase: 'La reforma de la Iglesia comienza por sus pastores.' },
  '04-20': { nombre: 'Santa Inés de Montepulciano', bio: 'Dominica italiana del siglo XIII, mística y priora desde los 20 años.', frase: 'La mística es el amor de Dios en su plenitud.' },
  '04-21': { nombre: 'San Anselmo de Canterbury', bio: 'Doctor de la Iglesia del siglo XI, el padre de la escolástica. Frase: la fe busca comprender.', frase: 'Credo ut intelligam — creo para comprender.' },
  '04-22': { nombre: 'San Sotero y San Cayo', bio: 'Papas mártires del siglo II-III que guiaron la Iglesia en tiempos de persecución romana.', frase: 'El pastor da la vida por sus ovejas.' },
  '04-23': { nombre: 'San Jorge Mártir', bio: 'Soldado mártir del siglo IV, patrono de Inglaterra, de los soldados y de los scouts. Muy popular.', frase: 'El cristiano es soldado de Cristo.' },
  '04-24': { nombre: 'San Fidel de Sigmaringa', bio: 'Primer mártir de la Congregación de Propaganda Fide del siglo XVII, capuchino misionero.', frase: 'La verdad no muere.' },
  '04-25': { nombre: 'San Marcos Evangelista', bio: 'Evangelista y compañero de San Pedro y San Pablo, autor del segundo Evangelio.', frase: 'Id por todo el mundo y proclamad el Evangelio.' },
  '04-26': { nombre: 'Nuestra Señora del Buen Consejo', bio: 'Advocación mariana muy venerada en Colombia, invocada para tomar buenas decisiones.', frase: 'María, Madre del Buen Consejo, guíanos.' },
  '04-27': { nombre: 'San Pedro Canisio', bio: 'Doctor de la Iglesia del siglo XVI, el segundo apóstol de Alemania, renovó la fe católica.', frase: 'El que tiene caridad, tiene todo.' },
  '04-28': { nombre: 'San Luis María Grignion de Montfort', bio: 'Misionero del siglo XVIII, autor de la Verdadera Devoción a María, muy influyente en Colombia.', frase: 'Todo a Jesús por María, todo a María para Jesús.' },
  '04-29': { nombre: 'Santa Catalina de Siena', bio: 'Doctora de la Iglesia del siglo XIV, mística y diplomática que convenció al Papa de volver a Roma.', frase: 'Sé quien eres y serás una antorcha para el mundo.' },
  '04-30': { nombre: 'San Pío V', bio: 'Papa del siglo XVI que impulsó el Concilio de Trento y reformó la Iglesia tras la Reforma protestante.', frase: 'La Iglesia se reforma desde adentro con oración y penitencia.' },
  '05-01': { nombre: 'San José Obrero', bio: 'Celebración del trabajo digno bajo el patronazgo de San José. Fiesta de guardar en Colombia.', frase: 'El trabajo santifica cuando se ofrece a Dios.' },
  '05-02': { nombre: 'San Atanasio de Alejandría', bio: 'Doctor de la Iglesia del siglo IV, defensor incansable de la divinidad de Cristo contra el arrianismo.', frase: 'Atanasio contra el mundo, el mundo contra Atanasio.' },
  '05-03': { nombre: 'Santos Felipe y Santiago', bio: 'Apóstoles de Jesús. Felipe preguntó a Jesús por el Padre y Santiago el Menor fue el primer obispo de Jerusalén.', frase: 'Señor, muéstranos al Padre y nos basta.' },
  '05-04': { nombre: 'Santa Mónica', bio: 'Madre de San Agustín, modelo de perseverancia en la oración por la conversión de su hijo.', frase: 'Las lágrimas de una madre no se pierden ante Dios.' },
  '05-05': { nombre: 'San Godardo de Hildesheim', bio: 'Obispo alemán del siglo XI, reformador monástico y constructor de iglesias.', frase: 'La belleza de la iglesia refleja la gloria de Dios.' },
  '05-06': { nombre: 'San Evodio de Antioquía', bio: 'Sucesor de San Pedro en Antioquía, uno de los primeros obispos de la historia cristiana.', frase: 'La sucesión apostólica es garantía de la fe.' },
  '05-07': { nombre: 'Santa Flavia Domitila', bio: 'Mártir romana del siglo I, sobrina del emperador Domiciano, desterrada por su fe cristiana.', frase: 'Cristo vale más que un trono imperial.' },
  '05-08': { nombre: 'San Víctor Maurus', bio: 'Soldado mártir africano del siglo III en Milán, patrono de los prisioneros.', frase: 'La libertad del alma no la puede quitar nadie.' },
  '05-09': { nombre: 'San Pacomio', bio: 'Fundador del cenobitismo en Egipto del siglo IV, organizó la vida comunitaria monástica.', frase: 'Juntos es más fácil llegar a Dios.' },
  '05-10': { nombre: 'San Juan de Ávila', bio: 'Doctor de la Iglesia del siglo XVI, apóstol de Andalucía y maestro espiritual de Santa Teresa.', frase: 'Amad a Dios mucho, porque bien lo merece.' },
  '05-11': { nombre: 'San Mamerto de Vienne', bio: 'Obispo del siglo V que instituyó las Rogativas para impetrar la protección divina.', frase: 'La oración comunitaria mueve el corazón de Dios.' },
  '05-12': { nombre: 'Santos Nereo y Aquileo', bio: 'Soldados mártires romanos del siglo I que abandonaron la milicia al convertirse al cristianismo.', frase: 'Solo hay un Señor: Jesucristo.' },
  '05-13': { nombre: 'Nuestra Señora de Fátima', bio: 'Aparición de la Virgen a tres pastorcitos en Portugal en 1917. Muy venerada en Colombia.', frase: 'Rezad el Rosario todos los días.' },
  '05-14': { nombre: 'San Matías Apóstol', bio: 'Elegido por sorteo para reemplazar a Judas entre los Doce Apóstoles.', frase: 'Dios elige a quien quiere para su misión.' },
  '05-15': { nombre: 'San Isidro Labrador', bio: 'Campesino madrileño del siglo XII, patrono de los agricultores y de Madrid. Muy venerado en zonas rurales de Colombia.', frase: 'El campo es el jardín de Dios.' },
  '05-16': { nombre: 'San Simón Stock', bio: 'General de los Carmelitas del siglo XIII a quien la Virgen entregó el escapulario del Carmen.', frase: 'El escapulario es el hábito de María.' },
  '05-17': { nombre: 'San Pascual Baylón', bio: 'Franciscano del siglo XVI, patrono de los congresos eucarísticos y de las asociaciones eucarísticas.', frase: 'La Eucaristía es el corazón de la Iglesia.' },
  '05-18': { nombre: 'San Juan I', bio: 'Papa mártir del siglo VI que viajó a Constantinopla para mediar por los cristianos ante el emperador arriano.', frase: 'El Papa es servidor de la paz.' },
  '05-19': { nombre: 'San Celestino V', bio: 'Papa ermitaño del siglo XIII que renunció al pontificado. Dante lo inmortalizó en la Divina Comedia.', frase: 'La humildad es la verdad sobre uno mismo.' },
  '05-20': { nombre: 'San Bernardino de Siena', bio: 'Franciscano del siglo XV, gran predicador que popularizó la devoción al Santo Nombre de Jesús.', frase: 'El nombre de Jesús es luz, alimento y medicina.' },
  '05-21': { nombre: 'San Cristóbal Magallanes', bio: 'Sacerdote mártir mexicano del siglo XX, ejecutado durante la persecución cristera.', frase: 'Muero inocente y perdono de corazón a mis asesinos.' },
  '05-22': { nombre: 'Santa Rita de Casia', bio: 'Agustina italiana del siglo XV, patrona de los imposibles y de las causas desesperadas. Muy venerada en Colombia.', frase: 'Con Dios nada es imposible.' },
  '05-23': { nombre: 'San Epitacio de Tuy', bio: 'Mártir del siglo I, discípulo de los Apóstoles, evangelizador de la Península Ibérica.', frase: 'El evangelio llega a todos los confines de la tierra.' },
  '05-24': { nombre: 'Nuestra Señora Auxiliadora', bio: 'Advocación mariana promovida por San Juan Bosco. Patrona de los Salesianos y muy venerada en Colombia.', frase: 'María Auxiliadora, rogad por nosotros.' },
  '05-25': { nombre: 'San Gregorio VII', bio: 'Papa reformador del siglo XI que defendió la independencia de la Iglesia ante los poderes civiles.', frase: 'He amado la justicia y odiado la iniquidad.' },
  '05-26': { nombre: 'San Felipe Neri', bio: 'Fundador del Oratorio del siglo XVI, el apóstol de Roma, conocido por su alegría y humor santo.', frase: 'La alegría es signo del Espíritu Santo.' },
  '05-27': { nombre: 'San Beda el Venerable', bio: 'Monje benedictino inglés del siglo VIII, Doctor de la Iglesia, padre de la historiografía inglesa.', frase: 'El estudio de la Escritura es camino de santidad.' },
  '05-28': { nombre: 'San Justo de Urgel', bio: 'Obispo español del siglo VI, autor de un comentario al Cantar de los Cantares.', frase: 'El amor de Dios supera todo entendimiento.' },
  '05-29': { nombre: 'San Maximino de Tréveris', bio: 'Obispo del siglo IV que acogió a San Atanasio durante su destierro y combatió el arrianismo.', frase: 'La hospitalidad abre las puertas del cielo.' },
  '05-30': { nombre: 'San Fernando III de Castilla', bio: 'Rey de Castilla del siglo XIII, reconquistador de Sevilla y Córdoba, muy venerado en España y Colombia.', frase: 'Gobernar es servir a Dios en los demás.' },
  '05-31': { nombre: 'Visitación de la Virgen María', bio: 'María visita a su prima Isabel que lleva en su seno a Juan el Bautista. Fiesta de la caridad fraternal.', frase: 'Mi alma glorifica al Señor.' },
  '06-01': { nombre: 'San Justino Mártir', bio: 'Filósofo y mártir del siglo II, el primer gran apologista cristiano que dialogó con la cultura griega.', frase: 'La filosofía verdadera conduce a Cristo.' },
  '06-02': { nombre: 'Santos Marcelino y Pedro', bio: 'Mártires romanos del siglo III, exorcista y sacerdote que convirtieron a su carcelero antes de morir.', frase: 'La fe convierte hasta en la cárcel.' },
  '06-03': { nombre: 'San Carlos Lwanga y Compañeros', bio: 'Mártires ugandeses del siglo XIX, jóvenes que murieron por rechazar los abusos del rey Mwanga.', frase: 'La pureza vale más que la vida.' },
  '06-04': { nombre: 'Santa Saturnina', bio: 'Mártir romana del siglo III, virgen que prefirió la muerte antes que renegar de su fe.', frase: 'La virginidad es anticipo del cielo.' },
  '06-05': { nombre: 'San Bonifacio de Maguncia', bio: 'Apóstol de Germania del siglo VIII, reorganizó la Iglesia en Europa central y murió mártir.', frase: 'El misionero siembra aunque no vea la cosecha.' },
  '06-06': { nombre: 'San Norberto de Xanten', bio: 'Fundador de los Premonstratenses del siglo XII, reformador de la vida canonical.', frase: 'La conversión radical es posible con la gracia de Dios.' },
  '06-07': { nombre: 'San Roberto de Newminster', bio: 'Abad cisterciense inglés del siglo XII, modelo de vida contemplativa y caridad.', frase: 'El silencio habla más que las palabras.' },
  '06-08': { nombre: 'San Medardo de Noyon', bio: 'Obispo del siglo VI que evangelizó el norte de Francia con gran celo apostólico.', frase: 'El evangelio transforma las culturas.' },
  '06-09': { nombre: 'San Efrén de Siria', bio: 'Doctor de la Iglesia del siglo IV, poeta y teólogo siríaco, llamado la Cítara del Espíritu Santo.', frase: 'La poesía es una forma de oración.' },
  '06-10': { nombre: 'San Asterio de Amasea', bio: 'Obispo del siglo IV, predicador elocuente que denunció las injusticias sociales de su tiempo.', frase: 'El obispo es voz de los sin voz.' },
  '06-11': { nombre: 'San Bernabé Apóstol', bio: 'Compañero de San Pablo en el primer viaje misionero, levita chipriota llamado hijo de la consolación.', frase: 'La consolación es un don del Espíritu.' },
  '06-12': { nombre: 'San Juan de Sahagún', bio: 'Agustino español del siglo XV, gran pacificador de Salamanca y predicador de la reconciliación.', frase: 'La paz es obra de la justicia.' },
  '06-13': { nombre: 'San Antonio de Padua', bio: 'Doctor de la Iglesia del siglo XIII, el santo más popular de Colombia. Patrono de los pobres y de las cosas perdidas.', frase: 'Si buscas milagros, mira donde estuvo Antonio.' },
  '06-14': { nombre: 'San Eliseo Profeta', bio: 'Sucesor del profeta Elías en el Antiguo Testamento, realizó grandes milagros en nombre de Dios.', frase: 'El espíritu de Elías descansa sobre Eliseo.' },
  '06-15': { nombre: 'San Vito', bio: 'Mártir siciliano del siglo III, patrono de los actores, los bailarines y los epilépticos.', frase: 'El martirio es el mayor testimonio de fe.' },
  '06-16': { nombre: 'San Juan Francisco Regis', bio: 'Jesuita francés del siglo XVII, misionero incansable entre los pobres de las montañas del Macizo Central.', frase: 'Los pobres son mi parroquia.' },
  '06-17': { nombre: 'San Gregorio Barbarigo', bio: 'Cardenal veneciano del siglo XVII, modelo de pastor que aplicó el Concilio de Trento en su diócesis.', frase: 'El Concilio se vive, no solo se estudia.' },
  '06-18': { nombre: 'San Gregorio de Cirta', bio: 'Obispo mártir del siglo IV en el norte de África durante la persecución de Diocleciano.', frase: 'La fe no se negocia.' },
  '06-19': { nombre: 'San Romualdo de Rávena', bio: 'Fundador de los Camaldulenses del siglo X, renovó el eremitismo occidental.', frase: 'Siéntate en tu celda como en el paraíso.' },
  '06-20': { nombre: 'San Silverio', bio: 'Papa mártir del siglo VI que murió exiliado por defender la ortodoxia contra la emperatriz Teodora.', frase: 'El Papa debe a Cristo obediencia, no al poder temporal.' },
  '06-21': { nombre: 'San Luis Gonzaga', bio: 'Jesuita del siglo XVI, patrono de los jóvenes católicos. Murió a los 23 años cuidando apestados.', frase: '¿Qué vale el mundo? Quiero a Dios.' },
  '06-22': { nombre: 'San Juan Fisher y Santo Tomás Moro', bio: 'Mártires ingleses del siglo XVI que murieron por defender el matrimonio y la autoridad del Papa.', frase: 'Soy el buen siervo del rey, pero primero de Dios.' },
  '06-23': { nombre: 'San José Cafasso', bio: 'Sacerdote turinés del siglo XIX, maestro de Don Bosco y capellán de los condenados a muerte.', frase: 'Nadie es tan pecador que no merezca misericordia.' },
  '06-24': { nombre: 'Natividad de San Juan Bautista', bio: 'Celebración del nacimiento del precursor de Cristo. Fiesta de guardar en Colombia.', frase: 'Es necesario que Él crezca y yo disminuya.' },
  '06-25': { nombre: 'San Guillermo de Monteverde', bio: 'Benedictino del siglo XII, ejemplo de conversión y vida contemplativa en Italia.', frase: 'La contemplación es el corazón de la Iglesia.' },
  '06-26': { nombre: 'San Josemaría Escrivá', bio: 'Fundador del Opus Dei del siglo XX, canonizó la santidad en el trabajo ordinario.', frase: 'Santificar el trabajo, santificarse en el trabajo, santificar a los demás.' },
  '06-27': { nombre: 'San Cirilo de Alejandría', bio: 'Doctor de la Iglesia del siglo V, defensor de la maternidad divina de María en el Concilio de Éfeso.', frase: 'María es verdaderamente Madre de Dios.' },
  '06-28': { nombre: 'San Ireneo de Lyon', bio: 'Doctor de la Iglesia del siglo II, primer gran teólogo sistemático y defensor de la fe apostólica.', frase: 'La gloria de Dios es el hombre viviente.' },
  '06-29': { nombre: 'Santos Pedro y Pablo', bio: 'Solemnidad de los dos pilares de la Iglesia. Pedro el pescador y Pablo el fariseo, ambos mártires en Roma.', frase: 'Tú eres Pedro y sobre esta roca edificaré mi Iglesia.' },
  '06-30': { nombre: 'Los Primeros Mártires de Roma', bio: 'Los cristianos quemados por Nerón en el año 64, las primeras víctimas de la persecución imperial.', frase: 'La sangre de los mártires es semilla de cristianos.' },
  '07-01': { nombre: 'San Junípero Serra', bio: 'Franciscano español que evangelizó California en el siglo XVIII. Canonizado por el Papa Francisco en 2015.', frase: 'Siempre adelante, nunca atrás.' },
  '07-02': { nombre: 'San Bernardino Realino', bio: 'Jesuita italiano del siglo XVI conocido por su caridad heroica con los pobres y enfermos.', frase: 'El amor de Dios es la fuente de toda santidad.' },
  '07-03': { nombre: 'Santo Tomás Apóstol', bio: 'Apóstol de Jesús que evangelizó la India. Pasó de la duda a proclamar su fe con el corazón.', frase: 'Señor mío y Dios mío.' },
  '07-04': { nombre: 'Santa Isabel de Portugal', bio: 'Reina del siglo XIII conocida como la Reina Santa, pacificadora y madre de los pobres.', frase: 'La paz es fruto de la justicia.' },
  '07-05': { nombre: 'San Antonio María Zaccaria', bio: 'Fundador de los Barnabitas del siglo XVI, renovó la vida cristiana con amor a la Eucaristía.', frase: 'La cruz es la llave del cielo.' },
  '07-06': { nombre: 'Santa María Goretti', bio: 'Mártir italiana de 12 años que murió perdonando a su agresor. Patrona de las jóvenes. Muy venerada en Colombia.', frase: 'Lo perdono y quiero que esté conmigo en el cielo.' },
  '07-07': { nombre: 'Beato Pedro Favre', bio: 'Primer jesuita ordenado sacerdote, compañero de San Ignacio, misionero en Europa.', frase: 'Todo para la mayor gloria de Dios.' },
  '07-08': { nombre: 'Santa Priscila', bio: 'Compañera de San Pablo en la primera generación cristiana, abrió su hogar para la Iglesia.', frase: 'La hospitalidad es una forma de amor.' },
  '07-09': { nombre: 'San Pedro Claver', bio: 'Jesuita del siglo XVII, apóstol de los esclavos en Cartagena de Indias. Patrono de Colombia.', frase: 'Esclavo de los negros para siempre.' },
  '07-10': { nombre: 'San Agustín Zhao Rong', bio: 'Mártir chino del siglo XIX, uno de los 120 mártires de China canonizados por Juan Pablo II.', frase: 'La sangre de los mártires es semilla de cristianos.' },
  '07-11': { nombre: 'San Benito de Nursia', bio: 'Padre del monaquismo occidental del siglo VI, fundador de la Orden Benedictina. Patrono de Europa.', frase: 'Ora et Labora — Reza y trabaja.' },
  '07-12': { nombre: 'San Juan Gualberto', bio: 'Fundador de los Vallombrosanos del siglo XI, perdonó al asesino de su hermano ante el crucifijo.', frase: 'El perdón libera más al que perdona.' },
  '07-13': { nombre: 'San Enrique II', bio: 'Emperador del Sacro Imperio Romano del siglo XI, modelo de gobernante cristiano y esposo fiel.', frase: 'El poder al servicio de Dios y del pueblo.' },
  '07-14': { nombre: 'San Camilo de Lelis', bio: 'Fundador de los Camilos del siglo XVI, patrono de los enfermos, enfermeros y hospitales.', frase: 'Ver a Cristo en el rostro del enfermo.' },
  '07-15': { nombre: 'San Buenaventura', bio: 'Doctor de la Iglesia del siglo XIII, ministro general de los franciscanos y gran teólogo místico.', frase: 'El camino hacia Dios pasa por el amor.' },
  '07-16': { nombre: 'Nuestra Señora del Carmen', bio: 'Patrona del Ejército colombiano y de los marineros. El escapulario del Carmen es signo de consagración a María.', frase: 'Quien muere con el escapulario del Carmen no sufrirá el fuego eterno.' },
  '07-17': { nombre: 'San Alejo', bio: 'Peregrino romano del siglo V que vivió como mendigo en casa de su propio padre sin ser reconocido.', frase: 'El que se humilla será enaltecido.' },
  '07-18': { nombre: 'San Federico de Utrecht', bio: 'Obispo mártir holandés del siglo IX que denunció el adulterio del rey y murió por ello.', frase: 'La verdad no puede callarse.' },
  '07-19': { nombre: 'San Vicente de Paúl', bio: 'Fundador de los Lazaristas y las Hijas de la Caridad del siglo XVII, apóstol de los pobres de París.', frase: 'Los pobres son nuestros señores y maestros.' },
  '07-20': { nombre: 'San Elías Profeta', bio: 'Gran profeta del Antiguo Testamento, defensor del Dios único en Israel contra los profetas de Baal.', frase: 'Solo el Señor es Dios.' },
  '07-21': { nombre: 'San Lorenzo de Brindis', bio: 'Doctor de la Iglesia del siglo XVI, capuchino y diplomático que frenó la invasión turca.', frase: 'La palabra de Dios es luz para el alma.' },
  '07-22': { nombre: 'Santa María Magdalena', bio: 'Primera testigo de la Resurrección, apóstol de los apóstoles. Jesús le apareció primero a ella.', frase: '¡He visto al Señor!' },
  '07-23': { nombre: 'Santa Brígida de Suecia', bio: 'Mística y fundadora del siglo XIV, madre de familia y patrona de Europa junto con Benedicto y Cirilo.', frase: 'El amor de Dios supera todo entendimiento.' },
  '07-24': { nombre: 'San Francisco Solano', bio: 'Franciscano andaluz del siglo XVI, apóstol de América del Sur, misionero en Perú y Argentina.', frase: 'La música es el idioma del alma.' },
  '07-25': { nombre: 'Santiago Apóstol', bio: 'Apóstol de Jesús, patrono de España y evangelizador de las Américas. Primer apóstol mártir.', frase: 'Hijo del trueno al servicio de Dios.' },
  '07-26': { nombre: 'Santos Joaquín y Ana', bio: 'Padres de la Virgen María y abuelos de Jesús. Patronos de los abuelos y de las familias.', frase: 'De raíces santas nacen frutos santos.' },
  '07-27': { nombre: 'San Pantaleón', bio: 'Médico mártir del siglo III, patrono de los médicos. Muy venerado en Colombia por su intercesión en enfermedades.', frase: 'Sanar el cuerpo es preparar el alma.' },
  '07-28': { nombre: 'San Nazario y Celso', bio: 'Mártires milaneses del siglo I, compañeros en la fe y en el martirio bajo la persecución romana.', frase: 'Unidos en Cristo, unidos en el martirio.' },
  '07-29': { nombre: 'Santa Marta', bio: 'Hermana de Lázaro y María Magdalena, modelo de fe activa y servicio. Muy venerada en Colombia.', frase: 'Sí, Señor, yo creo que tú eres el Cristo.' },
  '07-30': { nombre: 'San Pedro Crisólogo', bio: 'Doctor de la Iglesia del siglo V, arzobispo de Rávena conocido por sus homilías breves y profundas.', frase: 'La oración, el ayuno y la misericordia son las alas del alma.' },
  '07-31': { nombre: 'San Ignacio de Loyola', bio: 'Fundador de la Compañía de Jesús del siglo XVI, autor de los Ejercicios Espirituales. Muy venerado en Colombia.', frase: 'Todo para la mayor gloria de Dios.' },
  '08-01': { nombre: 'San Alfonso María de Ligorio', bio: 'Doctor de la Iglesia del siglo XVIII, fundador de los Redentoristas y patrono de los confesores.', frase: 'La oración es la llave del corazón de Dios.' },
  '08-02': { nombre: 'San Eusebio de Vercelli', bio: 'Obispo mártir del siglo IV, defensor de la divinidad de Cristo contra el arrianismo.', frase: 'Cristo es verdadero Dios y verdadero hombre.' },
  '08-03': { nombre: 'San Nicodemo', bio: 'Fariseo que visitó a Jesús de noche y luego ayudó a sepultarlo. Modelo de búsqueda sincera de la verdad.', frase: 'Nadie puede ver el Reino de Dios si no nace de nuevo.' },
  '08-04': { nombre: 'San Juan María Vianney', bio: 'Cura de Ars del siglo XIX, patrono de los párrocos. Pasaba hasta 16 horas diarias confesando.', frase: 'La oración es como la miel: cuanto más la pruebas, más dulce se vuelve.' },
  '08-05': { nombre: 'Dedicación de Santa María la Mayor', bio: 'Celebración de la basílica más antigua dedicada a María en Roma, construida en el siglo V.', frase: 'María es la morada de Dios entre los hombres.' },
  '08-06': { nombre: 'Transfiguración del Señor', bio: 'Jesús se transfigura ante Pedro, Santiago y Juan en el Monte Tabor, mostrando su gloria divina.', frase: 'Este es mi Hijo amado, escuchadle.' },
  '08-07': { nombre: 'San Cayetano de Thiene', bio: 'Fundador de los Teatinos del siglo XVI, reformador de la Iglesia y apóstol de la providencia divina.', frase: 'Confía en la providencia de Dios y no en la tuya.' },
  '08-08': { nombre: 'Santo Domingo de Guzmán', bio: 'Fundador de la Orden de Predicadores del siglo XIII, apóstol de la verdad y del Rosario.', frase: 'No hables sino con Dios o de Dios.' },
  '08-09': { nombre: 'Santa Teresa Benedicta de la Cruz', bio: 'Edith Stein, filósofa judía convertida al catolicismo, carmelita y mártir en Auschwitz en 1942.', frase: 'El que busca la verdad busca a Dios.' },
  '08-10': { nombre: 'San Lorenzo Mártir', bio: 'Diácono mártir romano del siglo III, patrono de los pobres y de los cocineros.', frase: 'Vuélveme, estoy asado por este lado.' },
  '08-11': { nombre: 'Santa Clara de Asís', bio: 'Fundadora de las Clarisas del siglo XIII, primera mujer que escribió una regla religiosa. Patrona de la televisión.', frase: 'La forma más alta de pobreza es la más alta riqueza.' },
  '08-12': { nombre: 'Santa Juana Francisca de Chantal', bio: 'Fundadora de las Visitandinas del siglo XVII junto con San Francisco de Sales.', frase: 'El amor de Dios basta para todo.' },
  '08-13': { nombre: 'Santos Ponciano e Hipólito', bio: 'Mártires romanos del siglo III, el Papa y su adversario teológico reconciliados ante el martirio.', frase: 'La muerte reconcilia lo que la vida separa.' },
  '08-14': { nombre: 'San Maximiliano Kolbe', bio: 'Franciscano polaco del siglo XX que dio su vida en Auschwitz para salvar a un padre de familia.', frase: 'El odio no es fuerza creadora, solo el amor lo es.' },
  '08-15': { nombre: 'Asunción de la Virgen María', bio: 'María es llevada en cuerpo y alma al cielo. Fiesta de guardar en Colombia, la más importante de agosto.', frase: 'Desde ahora me llamarán bienaventurada todas las generaciones.' },
  '08-16': { nombre: 'San Roque de Montpellier', bio: 'Peregrino francés del siglo XIV que cuidó apestados en Italia. Patrono de los enfermos de peste y epidemias.', frase: 'El que sirve a los enfermos sirve a Cristo.' },
  '08-17': { nombre: 'San Jacinto de Polonia', bio: 'Dominico del siglo XIII, apóstol de Europa del Norte, llevó el evangelio hasta Escandinavia y Rusia.', frase: 'El misionero no conoce fronteras.' },
  '08-18': { nombre: 'Santa Elena de la Cruz', bio: 'Madre del emperador Constantino del siglo IV, descubrió la Santa Cruz en Jerusalén.', frase: 'La cruz de Cristo es nuestra salvación.' },
  '08-19': { nombre: 'San Juan Eudes', bio: 'Fundador de los Eudistas del siglo XVII, apóstol de los Sagrados Corazones de Jesús y María.', frase: 'Los Corazones de Jesús y María son un solo corazón.' },
  '08-20': { nombre: 'San Bernardo de Claraval', bio: 'Doctor de la Iglesia del siglo XII, el último de los Padres, reformador cisterciense y consejero de papas.', frase: 'Amas a Dios sin medida el que lo ama más de lo que merece.' },
  '08-21': { nombre: 'San Pío X', bio: 'Papa del siglo XX que promovió la comunión frecuente y la catequesis. Reformó la liturgia y el derecho canónico.', frase: 'Renovar todo en Cristo.' },
  '08-22': { nombre: 'Reina de la Virgen María', bio: 'Celebración de María como Reina del cielo y de la tierra, coronada por la Santísima Trinidad.', frase: 'Dios te salve, Reina y Madre de misericordia.' },
  '08-23': { nombre: 'Santa Rosa de Lima', bio: 'Primera santa de América del siglo XVII, patrona de América Latina y de Filipinas. Muy venerada en Colombia.', frase: 'Fuera de la cruz no hay otra escalera para subir al cielo.' },
  '08-24': { nombre: 'San Bartolomé Apóstol', bio: 'Apóstol de Jesús identificado con Natanael, evangelizó Armenia y murió mártir desollado.', frase: 'Aquí hay un verdadero israelita en quien no hay engaño.' },
  '08-25': { nombre: 'San Luis IX de Francia', bio: 'Rey de Francia del siglo XIII, modelo de gobernante cristiano, justiciero y caritativo.', frase: 'El rey más grande es el más justo.' },
  '08-26': { nombre: 'San Ceferino', bio: 'Papa mártir del siglo III que gobernó la Iglesia durante la persecución de Septimio Severo.', frase: 'El pastor no abandona su rebaño.' },
  '08-27': { nombre: 'Santa Margarita de Cortona', bio: 'Penitente franciscana del siglo XIII que pasó de una vida de pecado a la santidad total.', frase: 'Nunca es tarde para volver a Dios.' },
  '08-28': { nombre: 'San Agustín de Hipona', bio: 'Doctor de la Iglesia del siglo IV, el mayor teólogo después de San Pablo. Convertido por su madre Mónica.', frase: 'Nos hiciste para Ti, Señor, y nuestro corazón está inquieto hasta que descanse en Ti.' },
  '08-29': { nombre: 'Martirio de San Juan Bautista', bio: 'Celebración del martirio del precursor de Cristo, decapitado por orden de Herodes a petición de Salomé.', frase: 'Es necesario que Él crezca y yo disminuya.' },
  '08-30': { nombre: 'Santa Genoveva Torres', bio: 'Fundadora de las Ángeles de los Hogares del siglo XX, amputada de una pierna desde los 8 años.', frase: 'El sufrimiento ofrecido a Dios se convierte en gozo.' },
  '08-31': { nombre: 'San Ramón Nonato', bio: 'Mercedario del siglo XIII nacido de una madre muerta, misionero en África redimiendo esclavos. Patrono de las embarazadas y parteras.', frase: 'La vida es un don de Dios que hay que proteger.' },
  '09-01': { nombre: 'San Gil Abad', bio: 'Ermitaño del siglo VII en Francia, patrono de los discapacitados y los mendigos.', frase: 'La debilidad humana es fuerza en Dios.' },
  '09-02': { nombre: 'San Esteban de Hungría', bio: 'Primer rey cristiano de Hungría del siglo X, evangelizó a su pueblo y organizó la Iglesia húngara.', frase: 'Un pueblo sin fe es un pueblo sin futuro.' },
  '09-03': { nombre: 'San Gregorio el Grande', bio: 'Papa del siglo VI que reorganizó la Iglesia, envió misioneros a Inglaterra y reformó la liturgia.', frase: 'Soy siervo de los siervos de Dios.' },
  '09-04': { nombre: 'Santa Rosa de Viterbo', bio: 'Terciaria franciscana del siglo XIII que predicaba en las calles siendo solo una niña.', frase: 'Los niños también pueden evangelizar.' },
  '09-05': { nombre: 'Santa Teresa de Calcuta', bio: 'Fundadora de las Misioneras de la Caridad del siglo XX, premio Nobel de la Paz. Muy venerada en Colombia.', frase: 'No todos podemos hacer grandes cosas, pero podemos hacer cosas pequeñas con gran amor.' },
  '09-06': { nombre: 'San Eleuterio de Bizancio', bio: 'Mártir del siglo III, soldado convertido que murió por negarse a renegar de Cristo.', frase: 'Cristo vale más que cualquier honor militar.' },
  '09-07': { nombre: 'Santa Regina', bio: 'Mártir gala del siglo III, virgen que prefirió la muerte antes que el matrimonio con un pagano.', frase: 'La virginidad consagrada es anticipo del cielo.' },
  '09-08': { nombre: 'Natividad de la Virgen María', bio: 'Celebración del nacimiento de María, la aurora que precede al Sol de justicia.', frase: 'Bendita eres entre todas las mujeres.' },
  '09-09': { nombre: 'San Pedro de Arbués', bio: 'Inquisidor aragonés del siglo XV, mártir asesinado mientras rezaba en la catedral de Zaragoza.', frase: 'La verdad de la fe vale la vida.' },
  '09-10': { nombre: 'San Nicolás de Tolentino', bio: 'Agustino italiano del siglo XIII, gran intercesor por las almas del purgatorio.', frase: 'Rezad por las almas del purgatorio.' },
  '09-11': { nombre: 'San Pafnucio', bio: 'Obispo confesor egipcio del siglo IV que perdió un ojo en la persecución de Diocleciano.', frase: 'Las cicatrices de la fe son trofeos del cielo.' },
  '09-12': { nombre: 'Santísimo Nombre de María', bio: 'Celebración del nombre de María, establecida para conmemorar la victoria de Viena sobre los turcos en 1683.', frase: 'El nombre de María es gozo en el corazón.' },
  '09-13': { nombre: 'San Juan Crisóstomo', bio: 'Doctor de la Iglesia del siglo IV, el mayor predicador de la historia cristiana. Arzobispo de Constantinopla.', frase: 'No puedo ver a Cristo hambriento si como en exceso.' },
  '09-14': { nombre: 'Exaltación de la Santa Cruz', bio: 'Celebración de la cruz como signo de salvación. Fiesta de gran devoción en Colombia.', frase: 'En la cruz está la salvación, la vida y la resurrección.' },
  '09-15': { nombre: 'Nuestra Señora de los Dolores', bio: 'Conmemoración de los siete dolores de María, especialmente su dolor al pie de la cruz.', frase: 'Una espada atravesará tu propia alma.' },
  '09-16': { nombre: 'Santos Cornelio y Cipriano', bio: 'Papa y obispo mártires del siglo III, ejemplo de unidad entre Roma y Cartago en tiempos de persecución.', frase: 'La unidad de la Iglesia es don del Espíritu.' },
  '09-17': { nombre: 'San Roberto Belarmino', bio: 'Doctor de la Iglesia del siglo XVI, defensor de la fe en tiempos de la Reforma protestante.', frase: 'La Iglesia es indefectible en la verdad.' },
  '09-18': { nombre: 'San José de Cupertino', bio: 'Franciscano del siglo XVII conocido por sus levitaciones durante la oración. Patrono de los estudiantes.', frase: 'El Espíritu Santo eleva al que se humilla.' },
  '09-19': { nombre: 'San Jenaro', bio: 'Obispo mártir napolitano del siglo III. Su sangre licuada es el milagro más famoso de Italia.', frase: 'La sangre del mártir clama al cielo.' },
  '09-20': { nombre: 'Santos Andrés Kim y Pablo Chong', bio: 'Mártires coreanos del siglo XIX, los primeros evangelizadores de Corea murieron por su fe.', frase: 'El evangelio transforma las culturas desde adentro.' },
  '09-21': { nombre: 'San Mateo Apóstol', bio: 'Publicano convertido por Jesús, evangelista y apóstol. Dejó todo al escuchar sígueme.', frase: 'Jesús vio a un hombre llamado Mateo y le dijo: Sígueme.' },
  '09-22': { nombre: 'San Mauricio y Compañeros', bio: 'Jefe de la legión tebana del siglo III que se negó a matar a cristianos y fue ejecutado con sus soldados.', frase: 'La conciencia no se vende ni por una orden del César.' },
  '09-23': { nombre: 'San Pío de Pietrelcina', bio: 'Capuchino del siglo XX con los estigmas de Cristo. Uno de los santos más populares en Colombia.', frase: 'Ora, espera y no te angusties.' },
  '09-24': { nombre: 'Nuestra Señora de las Mercedes', bio: 'Patrona de Colombia. Su fiesta es celebrada con gran devoción en todo el país.', frase: 'María de las Mercedes, intercede por Colombia.' },
  '09-25': { nombre: 'San Cleofás', bio: 'Discípulo de Emaús que reconoció a Jesús Resucitado en la fracción del pan.', frase: '¿No ardía nuestro corazón cuando nos hablaba en el camino?' },
  '09-26': { nombre: 'Santos Cosme y Damián', bio: 'Médicos mártires del siglo III, patronos de los médicos y farmacéuticos. Muy venerados en Colombia.', frase: 'La medicina es vocación de servicio.' },
  '09-27': { nombre: 'San Vincenzo de Paoli', bio: 'Fundador de las Conferencias de San Vicente, apóstol de la caridad organizada en el siglo XVII.', frase: 'La caridad organizada multiplica el bien.' },
  '09-28': { nombre: 'San Wenceslao de Bohemia', bio: 'Duque mártir checo del siglo X, patrono de Bohemia, asesinado por su hermano pagano.', frase: 'El cristiano sirve a Dios antes que al poder.' },
  '09-29': { nombre: 'Santos Arcángeles Miguel, Gabriel y Rafael', bio: 'Fiesta de los tres arcángeles mencionados en la Biblia. Muy venerados en Colombia, especialmente San Miguel.', frase: '¿Quién como Dios?' },
  '09-30': { nombre: 'San Jerónimo', bio: 'Doctor de la Iglesia del siglo IV, traductor de la Biblia al latín (Vulgata). Patrono de los biblistas.', frase: 'Ignorar las Escrituras es ignorar a Cristo.' },
  '10-01': { nombre: 'Santa Teresa del Niño Jesús', bio: 'Carmelita francesa del siglo XIX, Doctora de la Iglesia. Su camino de infancia espiritual es muy amado en Colombia.', frase: 'Mi vocación es el amor.' },
  '10-02': { nombre: 'Santos Ángeles Custodios', bio: 'Celebración de los ángeles guardianes que Dios asigna a cada persona. Muy venerados en Colombia.', frase: 'Su ángel siempre está viendo el rostro de mi Padre.' },
  '10-03': { nombre: 'San Francisco de Borja', bio: 'Jesuita del siglo XVI, virrey de Cataluña que abandonó el poder para servir a Dios.', frase: 'No serviré más a señor que se me pueda morir.' },
  '10-04': { nombre: 'San Francisco de Asís', bio: 'Fundador de los Franciscanos del siglo XIII, el santo más popular del mundo. Patrono de la ecología.', frase: 'Señor, hazme instrumento de tu paz.' },
  '10-05': { nombre: 'San Froilán de León', bio: 'Obispo español del siglo IX, reformador monástico y evangelizador del norte de España.', frase: 'La reforma comienza por uno mismo.' },
  '10-06': { nombre: 'San Bruno de Colonia', bio: 'Fundador de los Cartujos del siglo XI, maestro de teología que eligió la soledad contemplativa.', frase: 'O Bonitas — Oh Bondad.' },
  '10-07': { nombre: 'Nuestra Señora del Rosario', bio: 'Fiesta del Rosario establecida para conmemorar la victoria de Lepanto. El Rosario es muy rezado en Colombia.', frase: 'Rezad el Rosario todos los días.' },
  '10-08': { nombre: 'Santa Pelagia de Antioquía', bio: 'Penitente del siglo IV que pasó de una vida de pecado a la santidad mediante la conversión radical.', frase: 'Nunca es tarde para convertirse.' },
  '10-09': { nombre: 'San Dionisio Areopagita', bio: 'Convertido por San Pablo en Atenas, primer obispo de Atenas y patrono de Francia.', frase: 'La fe abre lo que la razón no puede alcanzar.' },
  '10-10': { nombre: 'San Daniel Comboni', bio: 'Obispo misionero italiano del siglo XIX, apóstol de África y fundador de los Combonianos.', frase: 'Salvar África con África.' },
  '10-11': { nombre: 'San Juan XXIII', bio: 'Papa del siglo XX que convocó el Concilio Vaticano II. Amado en Colombia por su sencillez y bondad.', frase: 'Veo todo, corrijo poco, dejo pasar mucho.' },
  '10-12': { nombre: 'Nuestra Señora del Pilar', bio: 'Primera aparición documentada de María al Apóstol Santiago en Zaragoza. Patrona de la Hispanidad.', frase: 'María se apareció sobre el pilar antes de morir.' },
  '10-13': { nombre: 'San Eduardo el Confesor', bio: 'Rey inglés del siglo XI, modelo de gobernante justo y piadoso. Construyó la Abadía de Westminster.', frase: 'El rey sirve a Dios sirviendo a su pueblo.' },
  '10-14': { nombre: 'San Calixto I', bio: 'Papa mártir del siglo III, antiguo esclavo que llegó a ser pontífice y murió por Cristo.', frase: 'Dios eleva a los humildes.' },
  '10-15': { nombre: 'Santa Teresa de Jesús', bio: 'Doctora de la Iglesia del siglo XVI, reformadora del Carmelo y mística extraordinaria. Muy venerada en Colombia.', frase: 'Nada te turbe, nada te espante, solo Dios basta.' },
  '10-16': { nombre: 'Santa Margarita María de Alacoque', bio: 'Visitandina del siglo XVII a quien Jesús reveló su Sagrado Corazón. Apóstol de esta devoción.', frase: 'He aquí el Corazón que tanto ha amado a los hombres.' },
  '10-17': { nombre: 'Beato Contardo Ferrini', bio: 'Jurista y profesor universitario italiano del siglo XIX-XX, modelo de laico santo dedicado al estudio y la oración.', frase: 'La ciencia y la santidad pueden ir de la mano.' },
  '10-18': { nombre: 'San Lucas Evangelista', bio: 'Médico y evangelista, compañero de San Pablo, autor del tercer Evangelio y de los Hechos de los Apóstoles.', frase: 'El Hijo del Hombre vino a buscar y salvar lo que estaba perdido.' },
  '10-19': { nombre: 'San Juan de Brébeuf y Compañeros', bio: 'Mártires jesuitas del siglo XVII en América del Norte, evangelizadores de los indios Hurón.', frase: 'El misionero da su vida por el evangelio.' },
  '10-20': { nombre: 'San Pablo de la Cruz', bio: 'Fundador de los Pasionistas del siglo XVIII, apóstol de la Pasión de Cristo.', frase: 'La Pasión de Cristo es el mayor acto de amor.' },
  '10-21': { nombre: 'San Hilarión', bio: 'Padre del monaquismo en Palestina del siglo IV, discípulo de San Antonio Abad.', frase: 'El desierto es el lugar donde Dios habla.' },
  '10-22': { nombre: 'San Juan Pablo II', bio: 'Papa del siglo XX que visitó Colombia en 1986. Uno de los papas más amados en la historia colombiana.', frase: 'No tengáis miedo. Abrid de par en par las puertas a Cristo.' },
  '10-23': { nombre: 'San Juan de Capistrano', bio: 'Franciscano del siglo XV, predicador itinerante que evangelizó Europa central y luchó contra los turcos.', frase: 'El predicador enciende corazones con la Palabra.' },
  '10-24': { nombre: 'San Antonio María Claret', bio: 'Fundador de los Claretianos del siglo XIX, arzobispo de Santiago de Cuba y confesor de la reina de España.', frase: 'El amor de Dios me consume.' },
  '10-25': { nombre: 'San Crisanto y Santa Daría', bio: 'Mártires romanos del siglo III, esposos que vivieron en virginidad consagrada y murieron juntos.', frase: 'El matrimonio cristiano es vocación de santidad.' },
  '10-26': { nombre: 'San Evaristo', bio: 'Papa mártir del siglo II que organizó las parroquias de Roma y murió bajo la persecución de Trajano.', frase: 'La Iglesia se organiza para servir mejor.' },
  '10-27': { nombre: 'San Frumencio', bio: 'Misionero del siglo IV, evangelizador de Etiopía, primer obispo de Axum.', frase: 'El evangelio llega a todos los pueblos.' },
  '10-28': { nombre: 'Santos Simón y Judas Tadeo', bio: 'Apóstoles de Jesús. San Judas Tadeo es el patrono de las causas desesperadas, muy venerado en Colombia.', frase: 'San Judas Tadeo, patrono de los imposibles.' },
  '10-29': { nombre: 'San Narciso de Jerusalén', bio: 'Obispo de Jerusalén del siglo II, centenario que gobernó su diócesis con sabiduría y santidad.', frase: 'La vejez santificada es corona de gloria.' },
  '10-30': { nombre: 'San Marcelo el Centurión', bio: 'Soldado romano mártir del siglo III que abandonó sus armas al convertirse al cristianismo.', frase: 'Solo hay un Señor: Jesucristo.' },
  '10-31': { nombre: 'San Wolfgango de Ratisbona', bio: 'Obispo del siglo X, reformador de la Iglesia en Bavaria y maestro del futuro emperador Enrique II.', frase: 'El obispo educa con su vida más que con sus palabras.' },
  '11-01': { nombre: 'Solemnidad de Todos los Santos', bio: 'Celebración de todos los santos del cielo, conocidos y desconocidos. Fiesta de guardar en Colombia.', frase: 'Bienaventurados los limpios de corazón porque ellos verán a Dios.' },
  '11-02': { nombre: 'Conmemoración de los Fieles Difuntos', bio: 'Día de oración por todas las almas del purgatorio. Gran tradición en Colombia de visitar cementerios.', frase: 'Señor, dales el descanso eterno y brille para ellos la luz perpetua.' },
  '11-03': { nombre: 'San Martín de Porres', bio: 'Dominico peruano del siglo XVII, mulato que cuidó pobres y animales. Muy venerado en Colombia.', frase: 'La caridad no tiene color de piel.' },
  '11-04': { nombre: 'San Carlos Borromeo', bio: 'Cardenal arzobispo de Milán del siglo XVI, modelo de pastor que aplicó el Concilio de Trento.', frase: 'El pastor huele a ovejas.' },
  '11-05': { nombre: 'San Zacarías e Isabel', bio: 'Padres de Juan el Bautista, modelo de matrimonio fiel que recibió el milagro de la fecundidad en la vejez.', frase: 'Para Dios nada hay imposible.' },
  '11-06': { nombre: 'San Leonardo de Noblac', bio: 'Ermitaño del siglo VI en Francia, patrono de los prisioneros y las mujeres en parto difícil.', frase: 'La libertad verdadera viene de Cristo.' },
  '11-07': { nombre: 'San Herculano de Perugia', bio: 'Obispo mártir del siglo VI que murió defendiendo su ciudad de los ostrogodos.', frase: 'El pastor da la vida por su pueblo.' },
  '11-08': { nombre: 'San Godofredo de Amiens', bio: 'Obispo reformador del siglo XI que luchó contra la simonía y el nicolaísmo en Francia.', frase: 'La Iglesia siempre necesita renovarse.' },
  '11-09': { nombre: 'Dedicación de la Basílica de Letrán', bio: 'La catedral del Papa en Roma, madre y cabeza de todas las iglesias del mundo.', frase: 'Esta es la casa de Dios y la puerta del cielo.' },
  '11-10': { nombre: 'San León Magno', bio: 'Papa y Doctor de la Iglesia del siglo V que detuvo a Atila y definió la naturaleza de Cristo.', frase: 'Cristo es verdadero Dios y verdadero hombre.' },
  '11-11': { nombre: 'San Martín de Tours', bio: 'Obispo del siglo IV, el soldado que partió su capa con un mendigo. Muy venerado en Colombia.', frase: 'Lo que hiciste al más pequeño, a mí me lo hiciste.' },
  '11-12': { nombre: 'San Josafat Kuntsevych', bio: 'Obispo mártir ucraniano del siglo XVII que murió buscando la unidad entre católicos y ortodoxos.', frase: 'Que todos sean uno.' },
  '11-13': { nombre: 'San Estanislao Kostka', bio: 'Jesuita polaco del siglo XVI que murió a los 18 años de amor por la Eucaristía. Patrono de los jóvenes.', frase: 'Nací para grandes cosas.' },
  '11-14': { nombre: 'San Serapión de Argel', bio: 'Mercedario mártir del siglo XIII que se entregó como rehén para liberar cautivos cristianos.', frase: 'Nadie tiene amor más grande que el que da la vida por sus hermanos.' },
  '11-15': { nombre: 'San Alberto Magno', bio: 'Doctor de la Iglesia del siglo XIII, maestro de Santo Tomás de Aquino, el primer científico cristiano.', frase: 'La ciencia y la fe se iluminan mutuamente.' },
  '11-16': { nombre: 'Santa Margarita de Escocia', bio: 'Reina escocesa del siglo XI, modelo de gobernante cristiana y madre ejemplar.', frase: 'El hogar cristiano es una pequeña Iglesia.' },
  '11-17': { nombre: 'Santa Isabel de Hungría', bio: 'Reina del siglo XIII que distribuyó sus riquezas entre los pobres siendo muy joven. Patrona de los terciarios franciscanos.', frase: 'Los pobres son Cristo en la tierra.' },
  '11-18': { nombre: 'San Román de Antioquía', bio: 'Diácono mártir del siglo IV que murió animando a los cristianos durante la persecución de Diocleciano.', frase: 'El diácono sirve a la Iglesia con su vida.' },
  '11-19': { nombre: 'Santa Matilde de Hackeborn', bio: 'Mística benedictina del siglo XIII, autora del Libro de la Gracia Especial.', frase: 'El Sagrado Corazón es el hogar del alma.' },
  '11-20': { nombre: 'San Edmundo de East Anglia', bio: 'Rey mártir inglés del siglo IX que murió antes que renegar de Cristo ante los vikingos.', frase: 'Cristo es mi rey y por Él muero.' },
  '11-21': { nombre: 'Presentación de la Virgen María', bio: 'Celebración de la consagración de María al Señor desde niña en el Templo de Jerusalén.', frase: 'María se consagró a Dios desde su infancia.' },
  '11-22': { nombre: 'Santa Cecilia', bio: 'Mártir romana del siglo III, patrona de los músicos y cantores. Muy venerada en Colombia.', frase: 'Cantad al Señor un cántico nuevo.' },
  '11-23': { nombre: 'San Clemente I', bio: 'Tercer sucesor de San Pedro, papa mártir del siglo I cuya carta a los corintios es la más antigua fuera del NT.', frase: 'La Iglesia de Roma preside en la caridad.' },
  '11-24': { nombre: 'San Andrés Dũng-Lạc y Compañeros', bio: '117 mártires vietnamitas del siglo XVIII-XIX, la Iglesia que nació del martirio en Asia.', frase: 'La sangre de los mártires es semilla de la Iglesia.' },
  '11-25': { nombre: 'Santa Catalina de Alejandría', bio: 'Mártir del siglo IV, filósofa que convenció a 50 sabios paganos y fue decapitada por el emperador.', frase: 'La sabiduría cristiana supera toda filosofía.' },
  '11-26': { nombre: 'San Silvestre Gozzolini', bio: 'Fundador de los Silvestrinos del siglo XIII, contemplativo que renovó la vida benedictina.', frase: 'En el silencio Dios habla.' },
  '11-27': { nombre: 'San Virgilio de Salzburgo', bio: 'Obispo irlandés del siglo VIII, evangelizador de Austria y Eslovenia, defensor de la redondez de la tierra.', frase: 'La fe no teme a la ciencia.' },
  '11-28': { nombre: 'San Jacobo de la Marca', bio: 'Franciscano del siglo XV, predicador itinerante que recorrió Europa promoviendo la paz y la fe.', frase: 'La paz de Cristo supera todo entendimiento.' },
  '11-29': { nombre: 'San Saturnino de Toulouse', bio: 'Primer obispo de Toulouse del siglo III, mártir arrastrado por un toro hasta la muerte.', frase: 'El martirio es el mayor testimonio de amor.' },
  '11-30': { nombre: 'San Andrés Apóstol', bio: 'Hermano de San Pedro, el primero en seguir a Jesús. Evangelizó Grecia y murió en cruz aspada.', frase: 'Hemos encontrado al Mesías.' },
  '12-01': { nombre: 'San Eligio de Noyon', bio: 'Obispo y orfebre del siglo VII, patrono de los orfebres, herreros y mecánicos.', frase: 'El trabajo bien hecho es oración.' },
  '12-02': { nombre: 'Santa Bibiana', bio: 'Mártir romana del siglo IV, virgen que murió azotada por negarse a renegar de Cristo.', frase: 'La virginidad es anticipo del cielo.' },
  '12-03': { nombre: 'San Francisco Javier', bio: 'Jesuita del siglo XVI, apóstol de Asia, bautizó a más de 30.000 personas. Patrono de las misiones.', frase: 'Aún más, Señor, aún más.' },
  '12-04': { nombre: 'San Juan Damasceno', bio: 'Doctor de la Iglesia del siglo VIII, defensor de las imágenes sagradas y último Padre de la Iglesia oriental.', frase: 'Las imágenes son la Biblia de los que no saben leer.' },
  '12-05': { nombre: 'San Sabas', bio: 'Abad del siglo V en Palestina, fundó la Gran Laura cerca de Jerusalén, centro del monaquismo palestino.', frase: 'El monje ora por el mundo desde el desierto.' },
  '12-06': { nombre: 'San Nicolás de Bari', bio: 'Obispo del siglo IV en Asia Menor, patrono de los niños y los marineros. Origen de la tradición de Santa Claus.', frase: 'La generosidad secreta es la más pura.' },
  '12-07': { nombre: 'San Ambrosio de Milán', bio: 'Doctor de la Iglesia del siglo IV, obispo que bautizó a San Agustín. Patrono de Milán y los estudiantes.', frase: 'Donde está Pedro, allí está la Iglesia.' },
  '12-08': { nombre: 'Inmaculada Concepción de María', bio: 'María concebida sin pecado original. Fiesta de guardar en Colombia, patrona de muchas iglesias colombianas.', frase: 'Soy la Inmaculada Concepción.' },
  '12-09': { nombre: 'San Juan Diego', bio: 'Indio mexicano del siglo XVI a quien se apareció la Virgen de Guadalupe. Patrono de los indígenas.', frase: '¿No estoy yo aquí que soy tu Madre?' },
  '12-10': { nombre: 'Nuestra Señora de Loreto', bio: 'La Santa Casa de Nazaret trasladada milagrosamente a Loreto en Italia. Centro de peregrinación mariana.', frase: 'María habitó en esta casa con Jesús y José.' },
  '12-11': { nombre: 'San Dámaso I', bio: 'Papa del siglo IV que encargó a San Jerónimo la traducción de la Biblia al latín.', frase: 'La Biblia es el alma de la teología.' },
  '12-12': { nombre: 'Nuestra Señora de Guadalupe', bio: 'Patrona de América Latina. Su imagen impresa en el tilma de Juan Diego es venerada en toda Colombia.', frase: '¿No estoy yo aquí que soy tu Madre?' },
  '12-13': { nombre: 'Santa Lucía', bio: 'Mártir siciliana del siglo III, patrona de los ciegos y los enfermos de la vista. Muy venerada en Colombia.', frase: 'Cristo es la luz verdadera que ilumina a todo hombre.' },
  '12-14': { nombre: 'San Juan de la Cruz', bio: 'Doctor de la Iglesia del siglo XVI, reformador del Carmelo junto con Santa Teresa. Poeta místico incomparable.', frase: 'En el atardecer de la vida te examinarán en el amor.' },
  '12-15': { nombre: 'San Valeriano de Abenza', bio: 'Mártir español del siglo III durante la persecución de Decio, modelo de fortaleza en la fe.', frase: 'La fe no cede ante la amenaza.' },
  '12-16': { nombre: 'San Adelaida de Borgoña', bio: 'Emperatriz del siglo X, modelo de gobernante cristiana y madre de familia ejemplar.', frase: 'El poder se ejerce con misericordia.' },
  '12-17': { nombre: 'San Lázaro de Betania', bio: 'Amigo de Jesús resucitado de entre los muertos. Patrono de los leprosos y los pobres.', frase: 'Jesús lloró — así amaba a los suyos.' },
  '12-18': { nombre: 'San Flaviano de Constantinopla', bio: 'Patriarca mártir del siglo V que defendió la naturaleza humana y divina de Cristo en el Concilio de Calcedonia.', frase: 'Cristo es verdadero Dios y verdadero hombre.' },
  '12-19': { nombre: 'San Timoteo de Antioquía', bio: 'Mártir sirio del siglo III que murió por negarse a entregar los textos sagrados a los romanos.', frase: 'La Palabra de Dios vale más que la vida.' },
  '12-20': { nombre: 'Santo Domingo de Silos', bio: 'Abad benedictino español del siglo XI que rescató cautivos y renovó la vida monástica en Castilla.', frase: 'La libertad es don de Dios.' },
  '12-21': { nombre: 'San Temístocles', bio: 'Mártir del siglo III que se entregó en lugar de un sacerdote perseguido, muriendo en su lugar.', frase: 'Dar la vida por otro es el amor más grande.' },
  '12-22': { nombre: 'Santa Francisca Javier Cabrini', bio: 'Primera ciudadana estadounidense canonizada, fundadora de los Misioneros del Sagrado Corazón.', frase: 'Con Dios y para Dios, todo lo puedo.' },
  '12-23': { nombre: 'San Juan de Kety', bio: 'Sacerdote polaco del siglo XV, profesor universitario conocido por su caridad con los pobres y estudiantes.', frase: 'Combate todos los errores pero nunca hagas daño a los hombres.' },
  '12-24': { nombre: 'San Adán y Santa Eva', bio: 'Vigilia de Navidad. La Iglesia recuerda a los primeros padres de la humanidad en espera del Redentor.', frase: 'Dios mismo vendrá a salvarnos.' },
  '12-25': { nombre: 'Natividad del Señor', bio: 'El Hijo de Dios nace en Belén. La mayor fiesta del año cristiano. Feliz Navidad Colombia.', frase: 'Os traigo una buena noticia, una gran alegría para todo el pueblo: hoy os ha nacido un Salvador.' },
  '12-26': { nombre: 'San Esteban Protomártir', bio: 'Primer mártir cristiano del siglo I, diácono lapidado mientras perdonaba a sus asesinos.', frase: 'Señor, no les tengas en cuenta este pecado.' },
  '12-27': { nombre: 'San Juan Apóstol', bio: 'El discípulo amado, el único apóstol que no murió mártir. Autor del cuarto Evangelio y el Apocalipsis.', frase: 'Dios es amor.' },
  '12-28': { nombre: 'Santos Inocentes Mártires', bio: 'Los niños asesinados por Herodes buscando al Niño Jesús. Patronos de los niños no nacidos.', frase: 'De la boca de los niños brota la alabanza.' },
  '12-29': { nombre: 'Santo Tomás Becket', bio: 'Arzobispo de Canterbury del siglo XII, mártir que murió defendiendo la independencia de la Iglesia.', frase: 'La Iglesia es libre o no es Iglesia.' },
  '12-30': { nombre: 'La Sagrada Familia', bio: 'Celebración de Jesús, María y José como modelo de toda familia cristiana. Muy venerada en Colombia.', frase: 'La familia que reza unida permanece unida.' },
  '12-31': { nombre: 'San Silvestre I', bio: 'Papa del siglo IV durante el reinado de Constantino, presidió el primer Concilio de Nicea.', frase: 'En Dios empieza y termina el año.' },
};

export default SANTOS;
