const VERSICULOS = {
  '01-01': { texto: 'El Señor te bendiga y te guarde.', referencia: 'Números 6, 24' },
  '01-02': { texto: 'En el principio existía el Verbo.', referencia: 'Juan 1, 1' },
  '01-03': { texto: 'El Señor es mi pastor, nada me falta.', referencia: 'Salmo 23, 1' },
  '01-04': { texto: 'Todo lo puedo en Cristo que me fortalece.', referencia: 'Filipenses 4, 13' },
  '01-05': { texto: 'Yo sé los planes que tengo para ustedes, planes de bienestar y no de calamidad.', referencia: 'Jeremías 29, 11' },
  '01-06': { texto: 'Al ver la estrella, se llenaron de inmensa alegría.', referencia: 'Mateo 2, 10' },
  '01-07': { texto: 'No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios.', referencia: 'Isaías 41, 10' },
  '01-08': { texto: 'Sé fuerte y valiente; no temas ni desmayes, porque el Señor tu Dios estará contigo.', referencia: 'Josué 1, 9' },
  '01-09': { texto: 'Sabemos que todas las cosas ayudan a bien a los que aman a Dios.', referencia: 'Romanos 8, 28' },
  '01-10': { texto: 'El amor es paciente, es bondadoso; el amor no tiene envidia.', referencia: '1 Corintios 13, 4' },
  '01-11': { texto: 'Vengan a mí todos los que están cansados y agobiados, y yo los haré descansar.', referencia: 'Mateo 11, 28' },
  '01-12': { texto: 'Quédense quietos, y sepan que yo soy Dios.', referencia: 'Salmo 46, 10' },
  '01-13': { texto: 'Confía en el Señor de todo corazón, y no te apoyes en tu propia prudencia.', referencia: 'Proverbios 3, 5' },
  '01-14': { texto: 'En el principio creó Dios los cielos y la tierra.', referencia: 'Génesis 1, 1' },
  '01-15': { texto: 'El Señor peleará por ustedes; ustedes quédense tranquilos.', referencia: 'Éxodo 14, 14' },
  '01-16': { texto: 'Sé fuerte y valiente, porque el Señor tu Dios va contigo; no te dejará ni te abandonará.', referencia: 'Deuteronomio 31, 6' },
  '01-17': { texto: 'El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.', referencia: 'Salmo 91, 1' },
  '01-18': { texto: 'Los que esperan en el Señor tendrán nuevas fuerzas; levantarán el vuelo como las águilas.', referencia: 'Isaías 40, 31' },
  '01-19': { texto: 'Practicar la justicia, amar la misericordia y caminar humildemente con tu Dios.', referencia: 'Miqueas 6, 8' },
  '01-20': { texto: 'El Señor tu Dios está en medio de ti como poderoso salvador.', referencia: 'Sofonías 3, 17' },
  '01-21': { texto: 'Las misericordias del Señor nunca terminan; sus compasiones no fallan.', referencia: 'Lamentaciones 3, 22' },
  '01-22': { texto: 'Yo soy el camino, la verdad y la vida.', referencia: 'Juan 14, 6' },
  '01-23': { texto: 'Ustedes son la luz del mundo.', referencia: 'Mateo 5, 14' },
  '01-24': { texto: 'Para Dios no hay nada imposible.', referencia: 'Lucas 1, 37' },
  '01-25': { texto: 'Saulo, Saulo, ¿por qué me persigues?', referencia: 'Hechos 9, 4' },
  '01-26': { texto: 'El fruto del Espíritu es amor, alegría, paz, paciencia, bondad.', referencia: 'Gálatas 5, 22' },
  '01-27': { texto: 'Por gracia han sido salvados mediante la fe.', referencia: 'Efesios 2, 8' },
  '01-28': { texto: 'La fe es la certeza de lo que se espera, la convicción de lo que no se ve.', referencia: 'Hebreos 11, 1' },
  '01-29': { texto: 'Depositen en él toda ansiedad, porque él cuida de ustedes.', referencia: '1 Pedro 5, 7' },
  '01-30': { texto: 'Dios es amor.', referencia: '1 Juan 4, 8' },
  '01-31': { texto: 'El Señor es mi luz y mi salvación, ¿a quién temeré?', referencia: 'Salmo 27, 1' },
  '02-01': { texto: 'Sirvan al Señor con alegría; vengan ante él con cánticos de júbilo.', referencia: 'Salmo 100, 2' },
  '02-02': { texto: 'Luz para alumbrar a las naciones, y gloria de tu pueblo Israel.', referencia: 'Lucas 2, 32' },
  '02-03': { texto: 'El Señor me ha dado lengua de discípulo, para saber sostener con una palabra al fatigado.', referencia: 'Isaías 50, 4' },
  '02-04': { texto: 'Hagan lo que hagan, trabajen de buena gana, como para el Señor y no para los hombres.', referencia: 'Colosenses 3, 23' },
  '02-05': { texto: 'Todo tiene su tiempo bajo el cielo, y todo lo que se quiere tiene su hora.', referencia: 'Eclesiastés 3, 1' },
  '02-06': { texto: 'A todo el que se declare por mí delante de los hombres, yo también me declararé por él delante de mi Padre.', referencia: 'Mateo 10, 32' },
  '02-07': { texto: 'Por nada se inquieten; más bien, presenten sus peticiones a Dios en toda oración.', referencia: 'Filipenses 4, 6' },
  '02-08': { texto: 'Para la libertad nos liberó Cristo.', referencia: 'Gálatas 5, 1' },
  '02-09': { texto: 'Gusten y vean qué bueno es el Señor.', referencia: 'Salmo 34, 8' },
  '02-10': { texto: 'Estén siempre firmes y constantes en la obra del Señor.', referencia: '1 Corintios 15, 58' },
  '02-11': { texto: 'Una mujer vestida del sol, con la luna bajo sus pies.', referencia: 'Apocalipsis 12, 1' },
  '02-12': { texto: 'Dichoso el que soporta la prueba, porque una vez que la haya superado recibirá la corona de la vida.', referencia: 'Santiago 1, 12' },
  '02-13': { texto: 'Te alabo porque me hiciste de manera formidable y maravillosa.', referencia: 'Salmo 139, 14' },
  '02-14': { texto: 'Todo lo excusa, todo lo cree, todo lo espera, todo lo soporta.', referencia: '1 Corintios 13, 7' },
  '02-15': { texto: 'En todo tiempo ama el amigo.', referencia: 'Proverbios 17, 17' },
  '02-16': { texto: 'Yo y mi casa serviremos al Señor.', referencia: 'Josué 24, 15' },
  '02-17': { texto: 'María guardaba todas estas cosas, meditándolas en su corazón.', referencia: 'Lucas 2, 19' },
  '02-18': { texto: 'Mi socorro viene del Señor, que hizo el cielo y la tierra.', referencia: 'Salmo 121, 2' },
  '02-19': { texto: 'No se amolden a este mundo; transfórmense mediante la renovación de su mente.', referencia: 'Romanos 12, 2' },
  '02-20': { texto: 'Mis pensamientos no son los pensamientos de ustedes, dice el Señor.', referencia: 'Isaías 55, 8' },
  '02-21': { texto: 'Proclama el mensaje; insiste a tiempo y a destiempo.', referencia: '2 Timoteo 4, 2' },
  '02-22': { texto: 'Tú eres Pedro, y sobre esta piedra edificaré mi Iglesia.', referencia: 'Mateo 16, 18' },
  '02-23': { texto: 'Sé fiel hasta la muerte, y yo te daré la corona de la vida.', referencia: 'Apocalipsis 2, 10' },
  '02-24': { texto: 'Crea en mí, oh Dios, un corazón limpio.', referencia: 'Salmo 51, 10' },
  '02-25': { texto: 'Yo, en cambio, espero en el Señor, en el Dios de mi salvación.', referencia: 'Miqueas 7, 7' },
  '02-26': { texto: 'Todo lo que pidan en oración, crean que ya lo han recibido, y lo obtendrán.', referencia: 'Marcos 11, 24' },
  '02-27': { texto: 'Acerquémonos, pues, con toda confianza al trono de la gracia.', referencia: 'Hebreos 4, 16' },
  '02-28': { texto: 'Él sana a los quebrantados de corazón, y venda sus heridas.', referencia: 'Salmo 147, 3' },
  '02-29': { texto: 'Den, y se les dará.', referencia: 'Lucas 6, 38' },
  '03-01': { texto: 'Rásguense el corazón y no las vestiduras, y conviértanse al Señor su Dios.', referencia: 'Joel 2, 13' },
  '03-02': { texto: 'El sacrificio agradable a Dios es un espíritu quebrantado.', referencia: 'Salmo 51, 17' },
  '03-03': { texto: 'El ayuno que yo quiero es este: soltar las cadenas injustas.', referencia: 'Isaías 58, 6' },
  '03-04': { texto: 'Cuando ayunen, no pongan cara triste como los hipócritas.', referencia: 'Mateo 6, 16' },
  '03-05': { texto: 'El reino de Dios está cerca; conviértanse y crean en el Evangelio.', referencia: 'Marcos 1, 15' },
  '03-06': { texto: 'El Señor es compasivo y misericordioso, lento a la ira y grande en amor.', referencia: 'Salmo 103, 8' },
  '03-07': { texto: 'Estos son los que vienen de la gran tribulación.', referencia: 'Apocalipsis 7, 14' },
  '03-08': { texto: 'Cuanto hicieron a uno de estos hermanos míos más pequeños, a mí me lo hicieron.', referencia: 'Mateo 25, 40' },
  '03-09': { texto: 'Donde esté tu tesoro, allí estará también tu corazón.', referencia: 'Lucas 12, 34' },
  '03-10': { texto: 'Señor, enséñame tus caminos; guíame por tu verdad.', referencia: 'Salmo 25, 4' },
  '03-11': { texto: 'Pidan y se les dará; busquen y encontrarán.', referencia: 'Mateo 7, 7' },
  '03-12': { texto: 'Aunque sus pecados sean como escarlata, quedarán blancos como la nieve.', referencia: 'Isaías 1, 18' },
  '03-13': { texto: 'Si alguno está en Cristo, es una nueva creación.', referencia: '2 Corintios 5, 17' },
  '03-14': { texto: 'Como busca la cierva corrientes de agua, así te busca, oh Dios, el alma mía.', referencia: 'Salmo 42, 1' },
  '03-15': { texto: 'Cuando todavía estaba lejos, su padre lo vio y se compadeció.', referencia: 'Lucas 15, 20' },
  '03-16': { texto: 'Antes eran tinieblas, mas ahora son luz en el Señor; anden como hijos de luz.', referencia: 'Efesios 5, 8' },
  '03-17': { texto: 'Dios no nos ha dado un espíritu de cobardía, sino de poder, de amor y de dominio propio.', referencia: '2 Timoteo 1, 7' },
  '03-18': { texto: 'Yo soy el pan de vida.', referencia: 'Juan 6, 35' },
  '03-19': { texto: 'José hizo como el ángel del Señor le había mandado, y recibió a su esposa.', referencia: 'Mateo 1, 24' },
  '03-20': { texto: 'Espero en el Señor, mi alma espera, y en su palabra confío.', referencia: 'Salmo 130, 5' },
  '03-21': { texto: 'Prosigo hacia la meta, para alcanzar el premio que Dios me llama a recibir en Cristo Jesús.', referencia: 'Filipenses 3, 14' },
  '03-22': { texto: 'Dios muestra su amor por nosotros en que, siendo aún pecadores, Cristo murió por nosotros.', referencia: 'Romanos 5, 8' },
  '03-23': { texto: 'Recibirán poder cuando el Espíritu Santo venga sobre ustedes, y serán mis testigos.', referencia: 'Hechos 1, 8' },
  '03-24': { texto: 'Nadie tiene amor más grande que el que da la vida por sus amigos.', referencia: 'Juan 15, 13' },
  '03-25': { texto: 'He aquí la esclava del Señor; hágase en mí según tu palabra.', referencia: 'Lucas 1, 38' },
  '03-26': { texto: 'Me mostrarás la senda de la vida; en tu presencia hay plenitud de gozo.', referencia: 'Salmo 16, 11' },
  '03-27': { texto: 'Yo soy la resurrección y la vida.', referencia: 'Juan 11, 25' },
  '03-28': { texto: 'Si confesamos nuestros pecados, él es fiel y justo para perdonarnos.', referencia: '1 Juan 1, 9' },
  '03-29': { texto: 'Él fue traspasado por nuestras rebeliones, molido por nuestras iniquidades.', referencia: 'Isaías 53, 5' },
  '03-30': { texto: 'Hacer las paces mediante la sangre de su cruz.', referencia: 'Colosenses 1, 20' },
  '03-31': { texto: 'Tanto amó Dios al mundo, que dio a su Hijo único.', referencia: 'Juan 3, 16' },
  '04-01': { texto: 'Cristo resucitó de entre los muertos, primicia de los que murieron.', referencia: '1 Corintios 15, 20' },
  '04-02': { texto: 'Así también la fe, si no tiene obras, está muerta.', referencia: 'Santiago 2, 17' },
  '04-03': { texto: 'Este es el día que hizo el Señor; alegrémonos y regocijémonos en él.', referencia: 'Salmo 118, 24' },
  '04-04': { texto: 'El temor del Señor es el principio de la sabiduría.', referencia: 'Proverbios 9, 10' },
  '04-05': { texto: 'Nos ha hecho renacer a una esperanza viva por la resurrección de Jesucristo.', referencia: '1 Pedro 1, 3' },
  '04-06': { texto: 'No teman; buscan a Jesús Nazareno, el crucificado; ha resucitado, no está aquí.', referencia: 'Marcos 16, 6' },
  '04-07': { texto: 'Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.', referencia: 'Proverbios 22, 6' },
  '04-08': { texto: 'Dichosos los que no vieron y creyeron.', referencia: 'Juan 20, 29' },
  '04-09': { texto: '¿No ardía nuestro corazón mientras nos hablaba en el camino?', referencia: 'Lucas 24, 32' },
  '04-10': { texto: 'Den gracias al Señor, porque él es bueno; su gran amor perdura para siempre.', referencia: 'Salmo 118, 1' },
  '04-11': { texto: 'No teman a los que matan el cuerpo, pero no pueden matar el alma.', referencia: 'Mateo 10, 28' },
  '04-12': { texto: 'Dios lo resucitó, poniendo fin a los dolores de la muerte.', referencia: 'Hechos 2, 24' },
  '04-13': { texto: 'Simón, hijo de Juan, ¿me amas más que estos?', referencia: 'Juan 21, 15' },
  '04-14': { texto: 'Fuimos sepultados con él por el bautismo para muerte, a fin de que andemos en vida nueva.', referencia: 'Romanos 6, 4' },
  '04-15': { texto: 'Se alegra mi corazón, se goza mi alma; también mi cuerpo reposa seguro.', referencia: 'Salmo 16, 9' },
  '04-16': { texto: 'Bienaventurados los limpios de corazón, porque ellos verán a Dios.', referencia: 'Mateo 5, 8' },
  '04-17': { texto: 'En ningún otro hay salvación.', referencia: 'Hechos 4, 12' },
  '04-18': { texto: 'La paz les dejo, mi paz les doy.', referencia: 'Juan 14, 27' },
  '04-19': { texto: '¿Dónde está, oh muerte, tu victoria?', referencia: '1 Corintios 15, 55' },
  '04-20': { texto: 'El Señor es bueno con todos, y compasivo con todas sus obras.', referencia: 'Salmo 145, 9' },
  '04-21': { texto: 'Si han resucitado con Cristo, busquen las cosas de arriba.', referencia: 'Colosenses 3, 1' },
  '04-22': { texto: 'Yo he venido para que tengan vida, y la tengan en abundancia.', referencia: 'Juan 10, 10' },
  '04-23': { texto: 'Vístanse con la armadura de Dios, para poder hacer frente a las asechanzas del diablo.', referencia: 'Efesios 6, 11' },
  '04-24': { texto: 'Para mí el vivir es Cristo, y el morir es ganancia.', referencia: 'Filipenses 1, 21' },
  '04-25': { texto: 'Vayan por todo el mundo y proclamen el Evangelio a toda criatura.', referencia: 'Marcos 16, 15' },
  '04-26': { texto: 'Una cosa pido al Señor, esta buscaré: habitar en la casa del Señor todos los días de mi vida.', referencia: 'Salmo 27, 4' },
  '04-27': { texto: 'Como el Padre me envió, también yo los envío.', referencia: 'Juan 20, 21' },
  '04-28': { texto: 'Ahí tienes a tu madre.', referencia: 'Juan 19, 27' },
  '04-29': { texto: 'Que Cristo habite por la fe en sus corazones.', referencia: 'Efesios 3, 17' },
  '04-30': { texto: 'Jesucristo es el mismo ayer, y hoy, y por los siglos.', referencia: 'Hebreos 13, 8' },
  '05-01': { texto: 'El Señor Dios tomó al hombre y lo puso en el jardín del Edén, para que lo cultivara y lo cuidara.', referencia: 'Génesis 2, 15' },
  '05-02': { texto: 'Pelea la buena batalla de la fe.', referencia: '1 Timoteo 6, 12' },
  '05-03': { texto: 'El que me ha visto a mí, ha visto al Padre.', referencia: 'Juan 14, 9' },
  '05-04': { texto: 'Oh Dios, tú eres mi Dios; te busco intensamente.', referencia: 'Salmo 63, 1' },
  '05-05': { texto: 'Ya no vivo yo, mas vive Cristo en mí.', referencia: 'Gálatas 2, 20' },
  '05-06': { texto: 'Miren cuánto nos ama el Padre, que nos llama hijos de Dios.', referencia: '1 Juan 3, 1' },
  '05-07': { texto: 'Mi alma anhela y aun desea con ansias los atrios del Señor.', referencia: 'Salmo 84, 2' },
  '05-08': { texto: 'Alégrate, llena de gracia, el Señor está contigo.', referencia: 'Lucas 1, 28' },
  '05-09': { texto: 'Yo soy la vid, ustedes los sarmientos.', referencia: 'Juan 15, 5' },
  '05-10': { texto: 'Tenemos este tesoro en vasijas de barro.', referencia: '2 Corintios 4, 7' },
  '05-11': { texto: 'Cercano está el Señor a todos los que lo invocan.', referencia: 'Salmo 145, 18' },
  '05-12': { texto: 'Yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré.', referencia: 'Apocalipsis 3, 20' },
  '05-13': { texto: 'Engrandece mi alma al Señor.', referencia: 'Lucas 1, 46' },
  '05-14': { texto: 'Muéstranos cuál de estos dos has escogido.', referencia: 'Hechos 1, 24' },
  '05-15': { texto: 'Visitas la tierra, y la riegas; en gran manera la enriqueces.', referencia: 'Salmo 65, 10' },
  '05-16': { texto: 'Sean pacientes, hermanos, hasta la venida del Señor. Miren cómo el labrador espera el fruto precioso de la tierra.', referencia: 'Santiago 5, 7' },
  '05-17': { texto: 'Esforzándonos por mantener la unidad del Espíritu en el vínculo de la paz.', referencia: 'Efesios 4, 3' },
  '05-18': { texto: 'He peleado la buena batalla, he acabado la carrera, he guardado la fe.', referencia: '2 Timoteo 4, 7' },
  '05-19': { texto: 'Envías tu Espíritu, y son creados, y renuevas la faz de la tierra.', referencia: 'Salmo 104, 30' },
  '05-20': { texto: 'Al nombre de Jesús se doble toda rodilla.', referencia: 'Filipenses 2, 10' },
  '05-21': { texto: 'El que quiera salvar su vida, la perderá; y el que pierda su vida por mi causa, la hallará.', referencia: 'Mateo 16, 25' },
  '05-22': { texto: 'Para los hombres es imposible, mas para Dios no; porque todas las cosas son posibles para Dios.', referencia: 'Marcos 10, 27' },
  '05-23': { texto: 'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.', referencia: 'Salmo 119, 105' },
  '05-24': { texto: 'Mientras Moisés tenía las manos alzadas, prevalecía Israel.', referencia: 'Éxodo 17, 11' },
  '05-25': { texto: 'En mi corazón he guardado tus dichos, para no pecar contra ti.', referencia: 'Salmo 119, 11' },
  '05-26': { texto: 'El gozo del Señor es vuestra fuerza.', referencia: 'Nehemías 8, 10' },
  '05-27': { texto: 'Vayan y hagan discípulos a todas las naciones.', referencia: 'Mateo 28, 19' },
  '05-28': { texto: 'Estén siempre alegres, oren sin cesar, den gracias en toda circunstancia.', referencia: '1 Tesalonicenses 5, 16' },
  '05-29': { texto: 'Canten al Señor un cántico nuevo.', referencia: 'Salmo 96, 1' },
  '05-30': { texto: 'Solamente esfuérzate y sé muy valiente.', referencia: 'Josué 1, 7' },
  '05-31': { texto: 'Bendita tú entre las mujeres, y bendito el fruto de tu vientre.', referencia: 'Lucas 1, 42' },
  '06-01': { texto: 'Estén siempre preparados para responder a todo el que les pida razón de la esperanza que hay en ustedes.', referencia: '1 Pedro 3, 15' },
  '06-02': { texto: 'Cercano está el Señor a los quebrantados de corazón, y salva a los contritos de espíritu.', referencia: 'Salmo 34, 18' },
  '06-03': { texto: 'Comparte penalidades como buen soldado de Jesucristo.', referencia: '2 Timoteo 2, 3' },
  '06-04': { texto: 'Ordena mis pasos con tu palabra, y ninguna iniquidad se enseñoree de mí.', referencia: 'Salmo 119, 133' },
  '06-05': { texto: 'Ellos salieron y predicaron por todas partes, colaborando el Señor con ellos.', referencia: 'Marcos 16, 20' },
  '06-06': { texto: 'No nos cansemos de hacer el bien, porque a su tiempo segaremos, si no desmayamos.', referencia: 'Gálatas 6, 9' },
  '06-07': { texto: 'Los cielos cuentan la gloria de Dios.', referencia: 'Salmo 19, 1' },
  '06-08': { texto: 'El agua que yo le daré se convertirá en él en una fuente de agua que salte para vida eterna.', referencia: 'Juan 4, 14' },
  '06-09': { texto: 'Que la palabra de Cristo habite en abundancia en ustedes, cantando con gracia en sus corazones.', referencia: 'Colosenses 3, 16' },
  '06-10': { texto: 'Deléitate asimismo en el Señor, y él te concederá las peticiones de tu corazón.', referencia: 'Salmo 37, 4' },
  '06-11': { texto: 'Era un hombre bueno, lleno del Espíritu Santo y de fe.', referencia: 'Hechos 11, 24' },
  '06-12': { texto: 'Somos colaboradores de Dios.', referencia: '1 Corintios 3, 9' },
  '06-13': { texto: 'Yo anduve errante como oveja extraviada; busca a tu siervo.', referencia: 'Salmo 119, 176' },
  '06-14': { texto: 'Que el Dios de la esperanza los llene de todo gozo y paz en el creer.', referencia: 'Romanos 15, 13' },
  '06-15': { texto: 'Cuán bueno y cuán agradable es que los hermanos convivan en armonía.', referencia: 'Salmo 133, 1' },
  '06-16': { texto: 'Hay diversidad de dones, pero el mismo Espíritu.', referencia: '1 Corintios 12, 4' },
  '06-17': { texto: 'Clemente y misericordioso es el Señor, lento para la ira y grande en misericordia.', referencia: 'Salmo 86, 15' },
  '06-18': { texto: 'Bendito sea el Dios y Padre de nuestro Señor Jesucristo, que nos bendijo con toda bendición espiritual.', referencia: 'Efesios 1, 3' },
  '06-19': { texto: 'Donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos.', referencia: 'Mateo 18, 20' },
  '06-20': { texto: 'Solo en Dios reposa mi alma; de él viene mi salvación.', referencia: 'Salmo 62, 1' },
  '06-21': { texto: 'Que ninguno tenga en poco tu juventud, sino sé ejemplo de los creyentes.', referencia: '1 Timoteo 4, 12' },
  '06-22': { texto: 'Corramos con paciencia la carrera que tenemos por delante.', referencia: 'Hebreos 12, 1' },
  '06-23': { texto: 'Bienaventurada la nación cuyo Dios es el Señor.', referencia: 'Salmo 33, 12' },
  '06-24': { texto: 'Será grande delante del Señor, y será lleno del Espíritu Santo.', referencia: 'Lucas 1, 15' },
  '06-25': { texto: 'Aquí estoy, envíame a mí.', referencia: 'Isaías 6, 8' },
  '06-26': { texto: 'Mi carne y mi corazón desfallecen; mas la roca de mi corazón y mi porción es Dios para siempre.', referencia: 'Salmo 73, 26' },
  '06-27': { texto: 'El Señor guardará tu salida y tu entrada desde ahora y para siempre.', referencia: 'Salmo 121, 8' },
  '06-28': { texto: 'Contender ardientemente por la fe que ha sido una vez dada a los santos.', referencia: 'Judas 1, 3' },
  '06-29': { texto: 'La iglesia oraba intensamente a Dios por Pedro.', referencia: 'Hechos 12, 5' },
  '06-30': { texto: 'Te basta mi gracia; porque mi poder se perfecciona en la debilidad.', referencia: '2 Corintios 12, 9' },
  '07-01': { texto: 'En quien tenemos redención por su sangre, el perdón de nuestros pecados.', referencia: 'Efesios 1, 7' },
  '07-02': { texto: 'El hacer tu voluntad, Dios mío, me ha agradado.', referencia: 'Salmo 40, 8' },
  '07-03': { texto: '¡Señor mío, y Dios mío!', referencia: 'Juan 20, 28' },
  '07-04': { texto: 'Ya no hay judío ni griego, porque todos ustedes son uno en Cristo Jesús.', referencia: 'Gálatas 3, 28' },
  '07-05': { texto: 'Busquen al Señor y su fortaleza; busquen siempre su rostro.', referencia: 'Salmo 105, 4' },
  '07-06': { texto: 'Dios enjugará toda lágrima de los ojos de ellos.', referencia: 'Apocalipsis 7, 17' },
  '07-07': { texto: 'Fiel es Dios, que no los dejará ser tentados más de lo que pueden resistir.', referencia: '1 Corintios 10, 13' },
  '07-08': { texto: 'Echa sobre el Señor tu carga, y él te sustentará.', referencia: 'Salmo 55, 22' },
  '07-09': { texto: 'A la verdad la mies es mucha, mas los obreros pocos.', referencia: 'Mateo 9, 37' },
  '07-10': { texto: 'La fe viene por el oír, y el oír, por la palabra de Dios.', referencia: 'Romanos 10, 17' },
  '07-11': { texto: 'Todo lo que te viniere a la mano para hacer, hazlo según tus fuerzas.', referencia: 'Eclesiastés 9, 10' },
  '07-12': { texto: 'Enséñame a hacer tu voluntad, porque tú eres mi Dios.', referencia: 'Salmo 143, 10' },
  '07-13': { texto: 'Estos son los que fueron sembrados en buena tierra, y dan fruto.', referencia: 'Marcos 4, 20' },
  '07-14': { texto: 'Estuve enfermo, y me visitaron.', referencia: 'Mateo 25, 36' },
  '07-15': { texto: 'Muchas aguas no podrán apagar el amor, ni lo ahogarán los ríos.', referencia: 'Cantares 8, 7' },
  '07-16': { texto: 'Con sus plumas te cubrirá, y debajo de sus alas estarás seguro.', referencia: 'Salmo 91, 4' },
  '07-17': { texto: 'Regocíjense en el Señor siempre. Otra vez digo: ¡Regocíjense!', referencia: 'Filipenses 4, 4' },
  '07-18': { texto: 'Amo al Señor, pues escuchó mi voz y mis súplicas.', referencia: 'Salmo 116, 1' },
  '07-19': { texto: 'En él vivimos, y nos movemos, y somos.', referencia: 'Hechos 17, 28' },
  '07-20': { texto: 'El Padre de misericordias y Dios de toda consolación.', referencia: '2 Corintios 1, 3' },
  '07-21': { texto: 'El Espíritu del Señor está sobre mí, porque me ha ungido para anunciar buenas nuevas.', referencia: 'Isaías 61, 1' },
  '07-22': { texto: 'María. — Rabuní, que quiere decir: Maestro.', referencia: 'Juan 20, 16' },
  '07-23': { texto: 'Esfuércense, y aliéntese su corazón, todos los que esperan en el Señor.', referencia: 'Salmo 31, 24' },
  '07-24': { texto: 'Vengan ustedes aparte a un lugar desierto, y descansen un poco.', referencia: 'Marcos 6, 31' },
  '07-25': { texto: '¿Pueden beber del vaso que yo he de beber?', referencia: 'Mateo 20, 22' },
  '07-26': { texto: 'Corona de los viejos son los nietos, y la honra de los hijos, sus padres.', referencia: 'Proverbios 17, 6' },
  '07-27': { texto: 'Bueno es alabar al Señor, y cantar salmos a tu nombre, oh Altísimo.', referencia: 'Salmo 92, 1' },
  '07-28': { texto: 'Nada nos podrá separar del amor de Dios.', referencia: 'Romanos 8, 38' },
  '07-29': { texto: 'Marta, Marta, cuidadosa y turbada estás con muchas cosas.', referencia: 'Lucas 10, 41' },
  '07-30': { texto: 'El Señor cumplirá su propósito en mí; oh Señor, tu misericordia es para siempre.', referencia: 'Salmo 138, 8' },
  '07-31': { texto: 'Haya, pues, en ustedes este sentir que hubo también en Cristo Jesús.', referencia: 'Filipenses 2, 5' },
  '08-01': { texto: 'Pero en ti hay perdón, para que seas temido.', referencia: 'Salmo 130, 4' },
  '08-02': { texto: 'Habrá más gozo en el cielo por un pecador que se arrepiente.', referencia: 'Lucas 15, 7' },
  '08-03': { texto: 'En el amor no hay temor, sino que el perfecto amor echa fuera el temor.', referencia: '1 Juan 4, 18' },
  '08-04': { texto: 'Os daré pastores según mi corazón.', referencia: 'Jeremías 3, 15' },
  '08-05': { texto: 'Porque el Señor ha elegido a Sion; la quiso para su morada.', referencia: 'Salmo 132, 13' },
  '08-06': { texto: 'Este es mi Hijo amado, en quien tengo complacencia; a él oíd.', referencia: 'Mateo 17, 5' },
  '08-07': { texto: 'Mirad las aves del cielo: vuestro Padre celestial las alimenta.', referencia: 'Mateo 6, 26' },
  '08-08': { texto: '¿Cómo creerán en aquel de quien no han oído? ¿Y cómo oirán sin haber quien les predique?', referencia: 'Romanos 10, 14' },
  '08-09': { texto: 'Lo considero todo como pérdida, a fin de ganar a Cristo.', referencia: 'Filipenses 3, 8' },
  '08-10': { texto: 'Dios ama al dador alegre.', referencia: '2 Corintios 9, 7' },
  '08-11': { texto: 'Los que miraron a él fueron alumbrados, y sus rostros no fueron avergonzados.', referencia: 'Salmo 34, 5' },
  '08-12': { texto: 'El amor cubre multitud de pecados.', referencia: '1 Pedro 4, 8' },
  '08-13': { texto: 'Ellos lo han vencido por medio de la sangre del Cordero.', referencia: 'Apocalipsis 12, 11' },
  '08-14': { texto: 'Yo soy el buen pastor; el buen pastor su vida da por las ovejas.', referencia: 'Juan 10, 11' },
  '08-15': { texto: 'Porque me ha hecho grandes cosas el Poderoso; santo es su nombre.', referencia: 'Lucas 1, 49' },
  '08-16': { texto: 'No te sobrevendrá mal, ni plaga tocará tu morada.', referencia: 'Salmo 91, 10' },
  '08-17': { texto: 'De la manera que habéis recibido al Señor Jesucristo, andad en él.', referencia: 'Colosenses 2, 6' },
  '08-18': { texto: 'En paz me acostaré, y asimismo dormiré; porque solo tú, Señor, me haces vivir confiado.', referencia: 'Salmo 4, 8' },
  '08-19': { texto: '¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo?', referencia: '1 Corintios 6, 19' },
  '08-20': { texto: 'Deseables son más que el oro; más dulces que la miel.', referencia: 'Salmo 19, 10' },
  '08-21': { texto: 'Dejad a los niños venir a mí, y no se lo impidáis.', referencia: 'Marcos 10, 14' },
  '08-22': { texto: 'A tu diestra está la reina con adorno de oro.', referencia: 'Salmo 45, 9' },
  '08-23': { texto: 'Yo soy la rosa de Sarón, y el lirio de los valles.', referencia: 'Cantares 2, 1' },
  '08-24': { texto: 'He aquí un verdadero israelita, en quien no hay engaño.', referencia: 'Juan 1, 47' },
  '08-25': { texto: 'Oh Dios, da tus juicios al rey, y tu justicia al hijo del rey.', referencia: 'Salmo 72, 1' },
  '08-26': { texto: 'Levántate y resplandece; porque ha venido tu luz, y la gloria del Señor ha nacido sobre ti.', referencia: 'Isaías 60, 1' },
  '08-27': { texto: 'Debían orar siempre, y no desfallecer.', referencia: 'Lucas 18, 1' },
  '08-28': { texto: 'Está mi alma apegada a ti; tu diestra me ha sostenido.', referencia: 'Salmo 63, 8' },
  '08-29': { texto: 'Herodes temía a Juan, sabiendo que era varón justo y santo.', referencia: 'Marcos 6, 20' },
  '08-30': { texto: 'Examíname, oh Dios, y conoce mi corazón.', referencia: 'Salmo 139, 23' },
  '08-31': { texto: 'Mantengamos firme, sin fluctuar, la profesión de nuestra esperanza.', referencia: 'Hebreos 10, 23' },
  '09-01': { texto: 'Enséñanos a contar nuestros días, para que traigamos al corazón sabiduría.', referencia: 'Salmo 90, 12' },
  '09-02': { texto: 'Corred de tal manera que lo obtengáis.', referencia: '1 Corintios 9, 24' },
  '09-03': { texto: 'El Hijo del Hombre no vino para ser servido, sino para servir.', referencia: 'Marcos 10, 45' },
  '09-04': { texto: 'Al Señor he puesto siempre delante de mí; porque está a mi diestra, no seré conmovido.', referencia: 'Salmo 16, 8' },
  '09-05': { texto: 'En cuanto no lo hicisteis a uno de estos más pequeños, tampoco a mí lo hicisteis.', referencia: 'Mateo 25, 45' },
  '09-06': { texto: 'Bienaventurado el hombre que teme al Señor, que en sus mandamientos se deleita en gran manera.', referencia: 'Salmo 112, 1' },
  '09-07': { texto: 'No os olvidéis de la hospitalidad, porque por ella algunos, sin saberlo, hospedaron ángeles.', referencia: 'Hebreos 13, 2' },
  '09-08': { texto: 'Tendrás gozo y alegría, y muchos se gozarán de su nacimiento.', referencia: 'Lucas 1, 14' },
  '09-09': { texto: 'No ya como siervo, sino como más que siervo, como hermano amado.', referencia: 'Filemón 1, 16' },
  '09-10': { texto: 'Alabad al Señor, porque él es bueno; porque para siempre es su misericordia.', referencia: 'Salmo 107, 1' },
  '09-11': { texto: 'Gozaos con los que se gozan; llorad con los que lloran.', referencia: 'Romanos 12, 15' },
  '09-12': { texto: '¿Quién es esta que se muestra como el alba?', referencia: 'Cantares 6, 10' },
  '09-13': { texto: 'He puesto mis palabras en tu boca.', referencia: 'Jeremías 1, 9' },
  '09-14': { texto: 'Lejos esté de mí gloriarme, sino en la cruz de nuestro Señor Jesucristo.', referencia: 'Gálatas 6, 14' },
  '09-15': { texto: 'Una espada atravesará tu misma alma.', referencia: 'Lucas 2, 35' },
  '09-16': { texto: 'Se requiere de los administradores, que cada uno sea hallado fiel.', referencia: '1 Corintios 4, 2' },
  '09-17': { texto: 'Cuán múltiples son tus obras, oh Señor; hiciste todas ellas con sabiduría.', referencia: 'Salmo 104, 24' },
  '09-18': { texto: 'Juntamente con él nos resucitó, y asimismo nos hizo sentar en los lugares celestiales.', referencia: 'Efesios 2, 6' },
  '09-19': { texto: 'Nuestra leve tribulación momentánea produce un eterno peso de gloria.', referencia: '2 Corintios 4, 17' },
  '09-20': { texto: 'A vosotros os es concedido a causa de Cristo, no solo que creáis en él, sino también que padezcáis por él.', referencia: 'Filipenses 1, 29' },
  '09-21': { texto: 'Sígueme. Y se levantó y le siguió.', referencia: 'Mateo 9, 9' },
  '09-22': { texto: 'El Señor es mi roca y mi castillo, y mi libertador.', referencia: 'Salmo 18, 2' },
  '09-23': { texto: 'Traigo en mi cuerpo las marcas del Señor Jesús.', referencia: 'Gálatas 6, 17' },
  '09-24': { texto: 'Redención ha enviado a su pueblo.', referencia: 'Salmo 111, 9' },
  '09-25': { texto: 'El Dios de paz os santifique por completo.', referencia: '1 Tesalonicenses 5, 23' },
  '09-26': { texto: 'Lo que tengo te doy: en el nombre de Jesucristo, levántate y anda.', referencia: 'Hechos 3, 6' },
  '09-27': { texto: 'Si un hermano o una hermana están desnudos, y tienen necesidad del mantenimiento de cada día.', referencia: 'Santiago 2, 15' },
  '09-28': { texto: 'Enjugará Dios toda lágrima de los ojos de ellos; ni habrá más muerte.', referencia: 'Apocalipsis 21, 4' },
  '09-29': { texto: 'Se libró una batalla en el cielo: Miguel y sus ángeles luchaban contra el dragón.', referencia: 'Apocalipsis 12, 7' },
  '09-30': { texto: 'Toda la Escritura es inspirada por Dios, y útil para enseñar.', referencia: '2 Timoteo 3, 16' },
  '10-01': { texto: 'Si no os volvéis y os hacéis como niños, no entraréis en el reino de los cielos.', referencia: 'Mateo 18, 3' },
  '10-02': { texto: 'Pues a sus ángeles mandará acerca de ti, que te guarden en todos tus caminos.', referencia: 'Salmo 91, 11' },
  '10-03': { texto: 'Tú formaste mis entrañas; tú me hiciste en el vientre de mi madre.', referencia: 'Salmo 139, 13' },
  '10-04': { texto: 'Alabadle, sol y luna; alabadle, todas las estrellas luminosas.', referencia: 'Salmo 148, 3' },
  '10-05': { texto: 'Alabad al Dios de los cielos, porque para siempre es su misericordia.', referencia: 'Salmo 136, 26' },
  '10-06': { texto: 'Después del fuego un silbo apacible y delicado.', referencia: '1 Reyes 19, 12' },
  '10-07': { texto: 'Porque ha mirado la bajeza de su sierva; desde ahora me dirán bienaventurada todas las generaciones.', referencia: 'Lucas 1, 48' },
  '10-08': { texto: 'El justo por su fe vivirá.', referencia: 'Habacuc 2, 4' },
  '10-09': { texto: 'Todo el que quiera salvar su vida, la perderá; y todo el que pierda su vida por causa de mí y del evangelio, la salvará.', referencia: 'Marcos 8, 35' },
  '10-10': { texto: 'Cosas que ojo no vio, ni oído oyó, son las que Dios ha preparado para los que le aman.', referencia: '1 Corintios 2, 9' },
  '10-11': { texto: 'Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios.', referencia: 'Mateo 5, 9' },
  '10-12': { texto: 'Desde el cabo de la tierra clamaré a ti; llévame a la roca que es más alta que yo.', referencia: 'Salmo 61, 2' },
  '10-13': { texto: 'Las cosas que se escribieron antes, para nuestra enseñanza se escribieron.', referencia: 'Romanos 15, 4' },
  '10-14': { texto: 'Bueno es el Señor para con los que en él esperan.', referencia: 'Nahúm 1, 7' },
  '10-15': { texto: 'Alma mía, en Dios solamente reposa.', referencia: 'Salmo 62, 5' },
  '10-16': { texto: 'Uno de los soldados le abrió el costado con una lanza, y al instante salió sangre y agua.', referencia: 'Juan 19, 34' },
  '10-17': { texto: 'Si el grano de trigo no cae en tierra y muere, queda solo; pero si muere, lleva mucho fruto.', referencia: 'Juan 12, 24' },
  '10-18': { texto: 'Os saluda Lucas el médico amado.', referencia: 'Colosenses 4, 14' },
  '10-19': { texto: 'Seréis aborrecidos de todos por causa de mi nombre; mas el que persevere hasta el fin, este será salvo.', referencia: 'Mateo 10, 22' },
  '10-20': { texto: 'Reconoced que el Señor es Dios; él nos hizo, y no nosotros a nosotros mismos.', referencia: 'Salmo 100, 3' },
  '10-21': { texto: 'La cual tenemos como segura y firme ancla del alma.', referencia: 'Hebreos 6, 19' },
  '10-22': { texto: 'No se turbe vuestro corazón; creéis en Dios, creed también en mí.', referencia: 'Juan 14, 1' },
  '10-23': { texto: 'Fortaleceos en el Señor, y en el poder de su fuerza.', referencia: 'Efesios 6, 10' },
  '10-24': { texto: '¡Cuán hermosos son sobre los montes los pies del que trae alegres nuevas!', referencia: 'Isaías 52, 7' },
  '10-25': { texto: 'He aquí, yo vengo pronto; retén lo que tienes, para que ninguno tome tu corona.', referencia: 'Apocalipsis 3, 11' },
  '10-26': { texto: 'Padre de huérfanos y defensor de viudas es Dios en su santa morada.', referencia: 'Salmo 68, 5' },
  '10-27': { texto: 'Vosotros sois linaje escogido, real sacerdocio, nación santa.', referencia: '1 Pedro 2, 9' },
  '10-28': { texto: 'Vosotros, amados, edificándoos sobre vuestra santísima fe.', referencia: 'Judas 1, 20' },
  '10-29': { texto: 'No dará tu pie al resbaladero, ni se dormirá el que te guarda.', referencia: 'Salmo 121, 3' },
  '10-30': { texto: 'Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria.', referencia: 'Filipenses 4, 19' },
  '10-31': { texto: 'Sed, pues, imitadores de Dios como hijos amados.', referencia: 'Efesios 5, 1' },
  '11-01': { texto: 'Una gran multitud, la cual nadie podía contar, de todas naciones y tribus.', referencia: 'Apocalipsis 7, 9' },
  '11-02': { texto: 'Las almas de los justos están en la mano de Dios, y no los tocará tormento alguno.', referencia: 'Sabiduría 3, 1' },
  '11-03': { texto: 'Tuve hambre, y me disteis de comer.', referencia: 'Mateo 25, 35' },
  '11-04': { texto: 'Si alguno anhela obispado, buena obra desea.', referencia: '1 Timoteo 3, 1' },
  '11-05': { texto: 'Mi corazón ha dicho de ti: Buscad mi rostro. Tu rostro buscaré, oh Señor.', referencia: 'Salmo 27, 8' },
  '11-06': { texto: 'Está establecido para los hombres que mueran una sola vez, y después el juicio.', referencia: 'Hebreos 9, 27' },
  '11-07': { texto: 'Se siembra en corrupción, resucitará en incorrupción.', referencia: '1 Corintios 15, 42' },
  '11-08': { texto: 'Estimada es a los ojos del Señor la muerte de sus santos.', referencia: 'Salmo 116, 15' },
  '11-09': { texto: '¿No sabéis que sois templo de Dios, y que el Espíritu de Dios mora en vosotros?', referencia: '1 Corintios 3, 16' },
  '11-10': { texto: 'Si alguno quiere venir en pos de mí, niéguese a sí mismo, y tome su cruz.', referencia: 'Mateo 16, 24' },
  '11-11': { texto: 'Por amor a vosotros se hizo pobre, siendo rico, para que con su pobreza fueseis enriquecidos.', referencia: '2 Corintios 8, 9' },
  '11-12': { texto: 'Que todos sean uno.', referencia: 'Juan 17, 21' },
  '11-13': { texto: 'Como a un natural de vosotros tendréis al extranjero que peregrine entre vosotros, y lo amaréis como a vosotros mismos.', referencia: 'Levítico 19, 34' },
  '11-14': { texto: 'El Señor guarda a los extranjeros; al huérfano y a la viuda sostiene.', referencia: 'Salmo 146, 9' },
  '11-15': { texto: 'El Señor da la sabiduría, y de su boca viene el conocimiento y la inteligencia.', referencia: 'Proverbios 2, 6' },
  '11-16': { texto: 'Toda tú eres hermosa, amiga mía, y en ti no hay mancha.', referencia: 'Cantares 4, 7' },
  '11-17': { texto: 'El que tiene bienes de este mundo, y ve a su hermano tener necesidad, y cierra contra él su corazón, ¿cómo mora el amor de Dios en él?', referencia: '1 Juan 3, 17' },
  '11-18': { texto: 'Cualquiera que me oye estas palabras, y las hace, le compararé a un hombre prudente, que edificó su casa sobre la roca.', referencia: 'Mateo 7, 24' },
  '11-19': { texto: 'Fuerza y honor son su vestidura; y se ríe de lo por venir.', referencia: 'Proverbios 31, 25' },
  '11-20': { texto: 'El reino de Dios no es comida ni bebida, sino justicia, paz y gozo en el Espíritu Santo.', referencia: 'Romanos 14, 17' },
  '11-21': { texto: 'Por este niño oraba, y el Señor me dio lo que le pedí.', referencia: '1 Samuel 1, 27' },
  '11-22': { texto: 'Alabadle con panderos y danzas; alabadle con cuerdas y flautas.', referencia: 'Salmo 150, 4' },
  '11-23': { texto: 'Yo soy el Alfa y la Omega, el principio y el fin.', referencia: 'Apocalipsis 22, 13' },
  '11-24': { texto: 'Bienaventurados los que padecen persecución por causa de la justicia, porque de ellos es el reino de los cielos.', referencia: 'Mateo 5, 10' },
  '11-25': { texto: 'Si alguno de vosotros tiene falta de sabiduría, pídala a Dios.', referencia: 'Santiago 1, 5' },
  '11-26': { texto: 'Entrad por sus puertas con acción de gracias, por sus atrios con alabanza.', referencia: 'Salmo 100, 4' },
  '11-27': { texto: 'Ofrezcamos siempre a Dios, por medio de él, sacrificio de alabanza.', referencia: 'Hebreos 13, 15' },
  '11-28': { texto: 'Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús.', referencia: '1 Tesalonicenses 5, 18' },
  '11-29': { texto: 'Venid, oh casa de Jacob, y caminemos a la luz del Señor.', referencia: 'Isaías 2, 5' },
  '11-30': { texto: 'Hemos hallado al Mesías, que traducido es, el Cristo.', referencia: 'Juan 1, 41' },
  '12-01': { texto: 'Ahora es más cerca de nosotros nuestra salvación que cuando creímos.', referencia: 'Romanos 13, 11' },
  '12-02': { texto: 'Oh Dios, restáuranos; haz resplandecer tu rostro, y seremos salvos.', referencia: 'Salmo 80, 3' },
  '12-03': { texto: '¡Ay de mí si no anunciare el evangelio!', referencia: '1 Corintios 9, 16' },
  '12-04': { texto: 'Voz del Señor sobre las aguas; truena el Dios de gloria.', referencia: 'Salmo 29, 3' },
  '12-05': { texto: 'Voz que clama en el desierto: Preparad camino al Señor.', referencia: 'Isaías 40, 3' },
  '12-06': { texto: 'Al Señor presta el que da al pobre, y él le dará su recompensa.', referencia: 'Proverbios 19, 17' },
  '12-07': { texto: 'No me envió Cristo a bautizar, sino a predicar el evangelio.', referencia: '1 Corintios 1, 17' },
  '12-08': { texto: 'Pondré enemistad entre ti y la mujer, y entre tu simiente y su simiente.', referencia: 'Génesis 3, 15' },
  '12-09': { texto: 'Él levanta del polvo al pobre, y del muladar exalta al menesteroso.', referencia: 'Salmo 113, 7' },
  '12-10': { texto: 'Vamos a su tabernáculo; postrémonos ante el estrado de sus pies.', referencia: 'Salmo 132, 7' },
  '12-11': { texto: 'Te daré las llaves del reino de los cielos.', referencia: 'Mateo 16, 19' },
  '12-12': { texto: 'Bienaventurada la que creyó, porque se cumplirá lo que le fue dicho de parte del Señor.', referencia: 'Lucas 1, 45' },
  '12-13': { texto: 'Yo soy la luz del mundo; el que me sigue, no andará en tinieblas.', referencia: 'Juan 8, 12' },
  '12-14': { texto: 'Si dijere: Ciertamente las tinieblas me encubrirán; aun la noche resplandecerá alrededor de mí.', referencia: 'Salmo 139, 11' },
  '12-15': { texto: 'Dios es salvación mía; me aseguraré y no temeré.', referencia: 'Isaías 12, 2' },
  '12-16': { texto: 'La misericordia y la verdad se encontraron; la justicia y la paz se besaron.', referencia: 'Salmo 85, 10' },
  '12-17': { texto: 'Saldrá una vara del tronco de Isaí, y un vástago retoñará de sus raíces.', referencia: 'Isaías 11, 1' },
  '12-18': { texto: 'Pero tú, Belén Efrata, de ti me saldrá el que será Señor en Israel.', referencia: 'Miqueas 5, 2' },
  '12-19': { texto: 'No temas, Zacarías, porque tu oración ha sido oída.', referencia: 'Lucas 1, 13' },
  '12-20': { texto: 'He aquí que la virgen concebirá, y dará a luz un hijo, y llamará su nombre Emmanuel.', referencia: 'Isaías 7, 14' },
  '12-21': { texto: 'Alzad, oh puertas, vuestras cabezas, y entrará el Rey de gloria.', referencia: 'Salmo 24, 7' },
  '12-22': { texto: 'Y mi espíritu se regocija en Dios mi Salvador.', referencia: 'Lucas 1, 47' },
  '12-23': { texto: 'Y se manifestará la gloria del Señor, y toda carne juntamente la verá.', referencia: 'Isaías 40, 5' },
  '12-24': { texto: 'Y dio a luz a su hijo primogénito, y lo envolvió en pañales, y lo acostó en un pesebre.', referencia: 'Lucas 2, 7' },
  '12-25': { texto: 'Que os ha nacido hoy, en la ciudad de David, un Salvador, que es Cristo el Señor.', referencia: 'Lucas 2, 11' },
  '12-26': { texto: 'Señor Jesús, recibe mi espíritu.', referencia: 'Hechos 7, 59' },
  '12-27': { texto: 'El discípulo a quien amaba Jesús.', referencia: 'Juan 21, 20' },
  '12-28': { texto: 'Voz fue oída en Ramá, grande lamentación; Raquel que llora por sus hijos.', referencia: 'Mateo 2, 18' },
  '12-29': { texto: 'Que estamos atribulados en todo, mas no angustiados.', referencia: '2 Corintios 4, 8' },
  '12-30': { texto: 'Y descendió con ellos, y vino a Nazaret, y estaba sujeto a ellos.', referencia: 'Lucas 2, 51' },
  '12-31': { texto: 'Sea la luz del Señor nuestro Dios sobre nosotros; confirma la obra de nuestras manos.', referencia: 'Salmo 90, 17' },
};

export default VERSICULOS;
